### ISSUE TITLE
[Error] Can't pin apps to the host's taskbar on SteamOS 3

### ISSUE THREAD

**Issue by csmbrad** [89luca89/distrobox#795] opened 2023-06-14 02:11 UTC
Please, before opening a bug:

- [x] make sure you've read the documentation. 
- [x] Ensure there isn't already an open issue about this.
- [x] Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
On SteamOS 3, when right-clicking the taskbar entry for an app running in the guest container, the "Pin to Task Manager" option is greyed out and inactive. 

**To Reproduce**
- Install Distrobox and Podman on SteamOS 3 pursuant to [the instructions.](https://github.com/89luca89/distrobox/blob/main/docs/posts/install_rootless.md)
- Create a container (I used Ubuntu 22.04)
- Install and run an application such as gedit
- Export the application with `distrobox-export`
- Right click on it from the task manager 
- "Pin to Task Manager" option will be greyed out

**Expected behavior**
The option to pin to the task manager should not be greyed out and should be active. When clicked,  it should result in the application being pinned like an app on the host system would be. A shortcut should appear on the taskbar, which when clicked runs the application. It should behave like a normal pinned app, indicating that the app is open and showing a preview of the window when hovered over.

**Logs**
The output of  `podman logs--latest` is attached here: [podman-log.txt](https://github.com/89luca89/distrobox/files/11740811/podman-log.txt)

**Desktop (please complete the following information):**
 - Are you using podman or docker? 
     - Podman
 - Which version or podman or docker?
     - 4.4.3 
 - Which version of distrobox?
     - 1.4.2.1

**Additional context**
Using a Steam Deck running SteamOS 3 version 3.4.8 on the Beta channel.

**Comment by 89luca89** [comment] 2023-08-04 20:20
This is related/duplicate of #728 

Without a WMClass you cannot pin an app

**Closed by 89luca89** 2023-08-04 20:20 UTC
Labels: bug
