### ISSUE TITLE
distrobox-assemble dismisses the home entry of an ini file with root=true

### ISSUE THREAD

**Issue by francoislaurent** [89luca89/distrobox#735] opened 2023-05-02 18:26 UTC
**Describe the bug**
Using `distrobox-assemble` and an ini file with both `root=true` and a `home` entry results in the specified home to be ignored.

In the guest system, the `$HOME` environment variable equals the host `$HOME`, and the specified home location is not created inside the guest system.

**To Reproduce**
```
#!/bin/sh

cat << EOT > test.ini
[test]
image=opensuse/leap:latest
home="/tmp/test"
root=true
EOT

distrobox-assemble create --replace -f test.ini

cat << EOT > test.sh
if [ "\$HOME" = "$HOME" ]; then
  echo "Host and guest homes are the same location"
fi
if ! [ -d "/tmp/test" ]; then
  echo "The specified guest home does not exist"
fi
EOT

distrobox-enter test -- bash test.sh
```
Sourcing the above script prints:
```
Host and guest homes are the same location
The specified guest home does not exist
```
Removing the `root=true` line leads to the expected behavior n°1.

**Expected behavior**
Two options:
1. the `home` entry is honored;
2. `distrobox-create` fails or warns that the `home` entry is not going to be honored.

**Desktop:**
```
$ podman --version
podman version 4.5.0
```
Distrobox was installed a few days ago with the `install` script and the `--next` flag.

**Additional context**
Host OS: MicroOS

I uninstalled distrobox to install the *next* version instead, because I need support for nvidia and I was also eager to try the `distrobox-assemble` approach.

--
Many thanks for this amazing tool!

**Comment by 89luca89** [comment] 2023-06-10 11:04
Hi @francoislaurent 
in some what this must have been fixed in some commits because I cannot reproduce this

Thanks anyway for the report!

**Closed by 89luca89** 2023-06-10 11:04 UTC
Labels: bug
