### ISSUE TITLE
[Error] yay not working in init_hooks distrobox assemble

### ISSUE THREAD

**Issue by RashiqAzhan** [89luca89/distrobox#1408] opened 2024-05-22 11:55 UTC
**Describe the bug**
yay not found and not working in init_hooks with distrobox assemble. Works as expected if container is start and the init_hooks are input manually in their order.

**To Reproduce**
Run `distrobox assemble create`.

distrobox.ini
```ini
[arch]
image=quay.io/toolbx/arch-toolbox:latest
pull=true
replace=true
start_now=true
additional_packages="git base-devel"
init_hooks=pacman -S --needed git base-devel;
init_hooks=cd yay-bin && makepkg -si;
init_hooks=yay -Sy --noconfirm keepassxc;
init_hooks=ln -s /usr/bin/distrobox-host-exec /usr/local/bin/docker
```

**Expected behavior**
Container building finishes without error and starts.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
[distrobox_assemble_create_--verbose.txt](https://github.com/89luca89/distrobox/files/15402741/distrobox_assemble_create_--verbose.txt)

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag
[podman_logs_--latest.txt](https://github.com/89luca89/distrobox/files/15402752/podman_logs_--latest.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? Podman
 - Which version or podman, docker or lilipod? 4.9.4
 - Which version of distrobox? 1.7.1.0
 - Which host distribution? Fedora Ublue - AuroraDX
 - How did you install distrobox? Built-in

**Comment by 89luca89** [comment] 2024-06-18 15:45
Duplicate of #1407 

And it has the same solution

**Closed by 89luca89** 2024-06-18 15:45 UTC
Labels: bug
