### ISSUE TITLE
[Error] distrobox enter archlinux fails with OCI runtime error (SteamOs - Steam Deck)

### ISSUE THREAD

**Issue by LyonSyonII** [89luca89/distrobox#406] opened 2022-09-10 20:56 UTC
Following the guide at [https://github.com/89luca89/distrobox/blob/main/docs/posts/install_on_steamos.md](https://github.com/89luca89/distrobox/blob/main/docs/posts/install_on_steamos.md) fails with:
```
Container arch is not running.
Starting container arch
run this command to follow along:

 podman logs -f arch

Error: OCI runtime error: unable to start container "f83f63e8e060a788d013f764337f5184e8fddbfab003a96a2417aadb5184c5f5": runc: runc create failed: unable to start container process: can't get final child's PID from pipe: EOF

An error occurred

An error occurred
```

Commands run:
`curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --next --prefix ~/.local`
`curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/extras/install-podman | sh -s -- --prefix ~/.local`
`distrobox create -i docker.io/library/archlinux:latest -n arch -Y -p`
`distrobox enter arch`

Both `podman` and `distrobox` are on PATH (added via `.bashrc`)

**Comment by 89luca89** [comment] 2022-09-11 09:23
Hi @LyonSyonII 

do you have both docker **and** podman installed? Or have both a system install of podman and this one?

Are you able to do:

```
podman run --rm -it --ipc host --name "my-distrobox" --network host --privileged --security-opt label=disable --user root:root --pid host  --env "SHELL=/bin/bash" --env "HOME=test" --volume /:/run/host:rslave --volume /dev:/dev:rslave --volume /sys:/sys:rslave --volume /tmp:/tmp:rslave --volume "test":"test":rslave --volume /sys/fs/selinux --volume /var/log/journal --volume /run/user/1000:/run/user/1000:rslave --volume /etc/hosts:/etc/hosts:ro --volume /etc/localtime:/etc/localtime:ro --volume /etc/resolv.conf:/etc/resolv.conf:ro --ulimit host --annotation run.oci.keep_original_groups=1 --mount type=devpts,destination=/dev/pts --userns keep-id docker.io/library/archlinux:latest /bin/bash
```

If not seems like a podman problem,
you can try doing these steps, **be aware this will delete all your podman containers**:

- podman system reset
- podman migrate

Then try again

**Comment by LyonSyonII** [comment] 2022-09-11 09:41
Tried running the command, fails with the same error.

Running 
```
podman system reset
podman system migrate
```
did not solve it, still same error.

**Comment by 89luca89** [comment] 2022-09-11 09:58
Thanks for trying

Can you post here the output of 

`podman info`

**Comment by LyonSyonII** [comment] 2022-09-11 10:00
```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /home/deck/.local/podman/lib/podman/conmon
    version: 'conmon version 2.1.3, commit: ab52a597278b20173440140cd810dc9fa8785c93'
  cpuUtilization:
    idlePercent: 96.01
    systemPercent: 1.43
    userPercent: 2.56
  cpus: 8
  distribution:
    codename: holo
    distribution: steamos
    variant: steamdeck
    version: 3.3.1
  eventLogger: file
  hostname: steamdeck
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 8560660480
  memTotal: 15557337088
  networkBackend: cni
  ociRuntime:
    name: runc
    package: Unknown
    path: /home/deck/.local/podman/bin/runc
    version: |-
      runc version 1.1.3
      commit: v1.1.3-0-g6724737
      spec: 1.0.2-dev
      go: go1.18.5
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /home/deck/.local/podman/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.2
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 0h 48m 38.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /home/deck/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
    overlay.mount_program:
      Executable: /home/deck/.local/podman/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 1.9
        fusermount3 version: 3.10.5
        FUSE library version 3.11.0
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /home/deck/.local/podman/lib/containers/storage
  graphRootAllocated: 49932861440
  graphRootUsed: 28432728064
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /home/deck/.local/podman/run/containers/storage
  volumePath: /home/deck/.local/podman//share/podman/volume
version:
  APIVersion: 4.2.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Comment by 89luca89** [comment] 2022-09-11 14:30
@LyonSyonII 

I was not able to reproduce on a fresh Steamdeck recovery image,
out of curiosity, can you try adding this flag and check if it solves the problem?

`distrobox create -a "--oom-score-adj 1000" -i docker.io/archlinux:latest -n arch`

and see if this works?

**Comment by LyonSyonII** [comment] 2022-09-11 14:43
Did not work either, same error.

**Comment by 89luca89** [comment] 2022-09-11 18:54
I have an idea, can you try this?

`wget "https://github.com/containers/crun/releases/download/1.6/crun-1.6-linux-amd64"`

then 

`cp crun-1.6-linux-amd64 ~/.local/podman/bin`

and

`chmod +x  ~/.local/podman/bin/crun`

Then you can do again

`podman system reset && podman system migrate`

and try again creating a container

Thanks a lot

**Comment by LyonSyonII** [comment] 2022-09-11 19:05
It worked now!
Seems like a problem with the podman version

**Comment by 89luca89** [comment] 2022-09-11 19:16
More like a runc vs crun problem
But I'll just add crun to the installation script :+1: 

Thanks for helping debugging :smile:

**Comment by 89luca89** [comment] 2022-09-11 19:40
Fixed in last commit :+1:

**Closed** 2022-09-11 19:39 UTC
Labels: bug

**Comment by andrewgribben** [comment] 2022-09-13 15:43
I've had to manually install crun using the method above as the install script seems to be grabbing HTML page content rather than the binary.

**Comment by 89luca89** [comment] 2022-09-13 16:29
@andrewgribben 

just noticed the scraping stopped working
pushed an update that works around this, thanks for reporting
