### ISSUE TITLE
xdg folder placement 

### ISSUE THREAD

**Issue by xensurve** [89luca89/distrobox#908] opened 2023-08-13 09:13 UTC
is there any implementation to have user configs from applications placed into one directory like flatpak/flatseal

I don't want to end up with a distro with user configs scattered all over my home directory  and  local share etc 
flatpak/flatseal helps with organising the home folder and system where it does'nt become a junk yard for configs

**Comment by 89luca89** [comment] 2023-08-13 12:41
This is a duplicate of #386 and #420

**Closed by 89luca89** 2023-08-13 12:41 UTC
Labels: enhancement
