### ISSUE TITLE
[Error] Docker & btrfs: "no space left on device" but there is space

### ISSUE THREAD

**Issue by wereii** [89luca89/distrobox#399] opened 2022-09-08 13:19 UTC
**Describe the bug**
Trying to enter any image results in error from docker about no space left but the disk and partition in question has plenty of space (only 16% used).

**To Reproduce**
- Arch Linux with Docker version 20.10.17, build 100c70180f, there are no other running containers in docker
- Docker on btrfs filesystem (encrypted LUKS)
- SSD disk of size 467GiB, **only 70GiB Used**
- create any image, I tried with `debian:latest` and default fedora toolbox
- try to enter the image

**Expected behavior**
Enter shell of the image in question without error

**Logs**
There are no logs for the docker container, it never starts

Verbose command:

```
+ case "${container_manager}" in
+ command -v podman
+ command -v docker
+ container_manager=docker
+ command -v docker
+ '[' 1 -ne 0 ']'
+ container_manager='docker --log-level debug'
+ '[' 0 -ne 0 ']'
+ container_home=/home/tomas
+ container_path=/home/tomas/bin:/home/tomas/.yarn/bin:/home/tomas/.config/yarn/global/node_modules/.bin:/home/tomas/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
+ '[' 0 -ne 0 ']'
+ container_status=unknown
++ docker --log-level debug inspect --type container deb --format 'container_status={{.State.Status}};
	{{range .Config.Env}}{{if slice . 0 5 | eq "HOME="}}container_home={{slice . 5 | printf "%q"}};{{end}}{{end}}
	{{range .Config.Env}}{{if slice . 0 5 | eq "PATH="}}container_path={{slice . 5 | printf "%q"}}{{end}}{{end}}'
+ eval 'container_status=created;
	container_home="/home/tomas";
	container_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"'
++ container_status=created
++ container_home=/home/tomas
++ container_path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ '[' created = unknown ']'
+ '[' created '!=' running ']'
+ printf 'Container %s is not running.\n' deb
Container deb is not running.
+ printf 'Starting container %s\n' deb
Starting container deb
+ printf 'run this command to follow along:\n\n'
run this command to follow along:

+ printf ' %s logs -f %s\n\n' 'docker --log-level debug' deb
 docker --log-level debug logs -f deb

+ docker --log-level debug cp /usr/bin/distrobox-init deb:/usr/bin/entrypoint
time="2022-09-08T14:39:43+02:00" level=debug msg="copying \"distrobox-init\" from \"/usr/bin\""
Error response from daemon: mount /sys:/var/lib/docker/btrfs/subvolumes/e3b8091a792f724487b99772f3d3342207f4ea9eba76a1f29533e8c33184478f/sys, flags: 0x5000: no space left on device
+ '[' 1 -ne 0 ']'
+ printf '\nAn error occurred\n'

An error occurred
+ rm -f '/home/tomas/.cache/.*.fifo' '/home/tomas/.cache/.*.status'

An error occurred
```

Docker log from systemd unit:
```
sep 08 14:44:55 tomas dockerd[16658]: time="2022-09-08T14:44:55.431340958+02:00" level=error msg="Handler for PUT /v1.41/containers/deb/archive returned error: mount /:/var/lib/docker/btrfs/subvolumes/c5a2db5bdd7b15eda49164958fa6e8deae5e00acab2d309db223fe1ab5f0401b/run/host, flags: 0x5000: no space left on device"
```

**Desktop (please complete the following information):**
- Docker version 20.10.17, build 100c70180f
- distrobox version: 1.4.0
 

**Additional context**

[Output of `lsblk -J /dev/mapper/cryptroot`](https://termbin.com/9xut)  
This is after installing and trying to enter the image.  
I am not sure how exactly docker mounts the image filesystem on btrfs (it does use btrfs subvolumes, duh) but according to the `lsblk`  output it almost seems like it loops infinitely thru the subvolume folder (which is (?) special btrfs subvolume mountpoint).

**Comment by 89luca89** [comment] 2022-09-08 14:21
Hi @wereii 

Can you run a normal docker?

Like

`docker run -it debian:latest /bin/bash`

**Comment by wereii** [comment] 2022-09-08 14:28
Yeah absolutely from alpine to postgres, this only occurs with `distrobox`.

**Comment by wereii** [comment] 2022-09-08 15:22
I have found a solution (not that I did understand the problem in a first place).

https://www.reddit.com/r/docker/comments/mba2c7/comment/grxwudz/?context=3

I have a disk setup with both root `/` and `/home` mounted as btrfs subvolumes (subvolume -> mountpoint):
- `@ -> /`
- `@home -> /home`

By default, docker creates a subvolume at **/**`var/lib/docker/btrfs` which is obviously inside the root subvolume `@`.

According to the reddit comment I linked, btrfs automatically mounts nested subvolumes for you (`/`, `/var/lib/docker/btrfs`).  
So if `distrobox` tries to mount the host root filesystem (`@ -> /`) somewhere then it also mounts the `/var/lib/docker/btrfs/subvolume/<container layers subvolume>`, which will contain a subvol of the root and docker btrfs subvol then it's own subvol, etc... (?)

#### Solution
"Move" the `/var/lib/docker/btrfs` subvolume into root btrfs subvolume so it's not nested inside your system root.

- `mount -o 'subvolid=0'  <the real disk path in question> /mnt/btrfs_root` - mount the absolute root/parent subvolume somewhere
- `btrfs create subvolume /mnt/btrfs_root/@docker`
- `systemctl stop docker`
- cp -r /var/lib/docker/btrfs/*  /mnt/btrfs_root/@docker/ - **I didn't try this, I had no data in docker so I simply deleted the whole subvolume later**
- `umount /var/lib/docker/btrfs`
- `mount -o 'subvolume=@docker' /var/lib/docker/btrfs`
- Add the above mount to fstab to make it permanent

**Comment by nPHYN1T3** [comment] 2022-09-10 17:44
Affected, not sure how this isn't a distrobox issue when the docker commands work by themselves but once you toss distrobox into the mix everything fails.

**Comment by nPHYN1T3** [comment] 2022-09-10 18:11
And so the fix is what?

**Comment by wereii** [comment] 2022-09-12 09:19
@nPHYN1T3 If you can somehow tell btrfs to not auto-mount the nested docker subvolume then that should work too (but then you will have to add it to fstab).

Otherwise I guess the only sound solution is to not have containers subvolumes nested in root subvolume, eg. move it to the absolute root as I describe in my solution.

**Comment by tjssoldier** [comment] 2022-09-15 09:44
So this is a docker bug? I was using distrobox with btrfs and docker normally. Then I decide to make a fresh install of my system and this error beginning to happen.

**Comment by nPHYN1T3** [comment] 2022-09-15 20:51
Yeah docker works for me, as soon as you add distrobox...dead. However "no fix/won't fix" so...

**Comment by 89luca89** [comment] 2022-09-15 23:52
@nPHYN1T3 hi

Can you confirm that


`docker run -v /var:/var -v $HOME,:$HOME image:tag sh`

Works?

**Comment by nPHYN1T3** [comment] 2022-09-16 00:27
Seems to work fine. Pulls the image and all that.

**Comment by 89luca89** [comment] 2022-09-16 07:48
> Seems to work fine. Pulls the image and all that.

Can you do another test?

```console
docker run --rm -it --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --volume /:/run/host:rslave --volume /dev:/dev:rslave --volume /sys:/sys:rslave --volume /tmp:/tmp:rslave --volume $HOME:$HOME:rslave --volume /sys/fs/selinux --volume /var/log/journal --volume /run/user:/run/user:rslave --volume /etc/hosts:/etc/hosts:ro --volume /etc/localtime:/etc/localtime:ro --volume /etc/resolv.conf:/etc/resolv.conf:ro IMAGE:TAG /bin/sh
```

This has all the mountpoints that distrobox does

**Comment by nPHYN1T3** [comment] 2022-09-16 08:00
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/var/lib/docker/volumes/32a5c48d6de928a850c1757e8bcd804eef9995a39a0291433d4b88b4ed4b9964/_data" to rootfs at "/sys/fs/selinux": mkdir /var/lib/docker/btrfs/subvolumes/ecc3f91ef9f454bf10780dd12f1867f17efb566f5b9ff61908facea65f20286e/sys/fs/selinux: operation not permitted: unknown.

Works fine if I do a normal docker run.

**Comment by 89luca89** [comment] 2022-09-16 08:07
Reopening for further investivagion

Seems like a regression in 1.4.0, can anyone who has this problem check if 1.3.1 works?

**Comment by nPHYN1T3** [comment] 2022-09-16 08:09
I can't, downgrade only has current.

**Comment by peterurbanec** [comment] 2022-09-16 08:15
I can run the same image under `1.3.1` with no issues.

**Comment by 89luca89** [comment] 2022-09-16 08:23
It seems like `docker` with `btrfs` does not like the `docker cp` command
This was introduced in 1.4.0, so that's why it works with 1.3.1

To confirm, can anyone test the following:

```console
docker create --name TEST --ipc host --network host --privileged --security-opt label=disable --user root:root --pid host --volume /:/run/host:rslave --volume /dev:/dev:rslave --volume /sys:/sys:rslave --volume /tmp:/tmp:rslave --volume $HOME:$HOME:rslave --volume /run/user:/run/user:rslave --volume /etc/hosts:/etc/hosts:ro --volume /etc/localtime:/etc/localtime:ro --volume /etc/resolv.conf:/etc/resolv.conf:ro IMAGE:TAG /bin/sh
```

and then just try to copy a file in it

```console
docker cp /etc/hosts TEST:/usr
```

**Comment by peterurbanec** [comment] 2022-09-16 08:26
```
$ git bisect bad
52a34fbd52e1f0f035657b167ebe997d41db0993 is the first bad commit
commit 52a34fbd52e1f0f035657b167ebe997d41db0993
Author: Luca Di Maio <luca.dimaio1@gmail.com>
Date:   Tue Jul 12 22:58:53 2022 +0200

    create: move distrobox utility mounts into enter

    Instead of hard mounting the utilities during create, let's use
    podman/docker cp utility to copy them inside the container, durig the
    start phase.
    This should ensure more flexibility in case someone wants to move
    distrobox in other installation paths (eg: from /usr/bin to
    ~/.local/bin), or on systems like Nix where it's all done with changin
    symlinks.

    Fix #315

    Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>

 distrobox-create | 24 +-----------------------
 distrobox-enter  | 21 +++++++++++++++++++++
 2 files changed, 22 insertions(+), 23 deletions(-)
```

**Comment by 89luca89** [comment] 2022-09-16 08:26
It's a docker bug it seems:

https://github.com/moby/moby/issues/38995

**Comment by nPHYN1T3** [comment] 2022-09-16 08:31
For years I've read about how easy it is to spin up XYZ on "containerization" and for years I've yet to ever see it work hehe.

**Comment by 89luca89** [comment] 2022-09-16 08:32
Well podman just works :shrug: 

It looks like an inherent issue with how `docker cp` is engineered  (looking at the bug discussion upstream)
Will see if I can find a way to work around this, but I'm not sure how

**Comment by peterurbanec** [comment] 2022-09-16 08:54
Is it possible to switch an existing installation between docker and podman?

**Comment by 89luca89** [comment] 2022-09-16 08:57
> Is it possible to switch an existing installation between docker and podman?

you can yes

you can use this to save the container as a tar.gz:
https://docs.docker.com/engine/reference/commandline/export/

and then use this to load it back into podman:
https://docs.podman.io/en/latest/markdown/podman-import.1.html

This will give you an image, that you can use as a base to run `distrobox create -i THATIMAGE -n ...`

**Comment by nPHYN1T3** [comment] 2022-09-16 09:02
Tried with podman, no dice.

**Comment by nPHYN1T3** [comment] 2022-09-16 09:10
It means it doesn't work with podman ;p

**Comment by 89luca89** [comment] 2022-09-16 09:12
> It means it doesn't work with podman ;p

Distrobox in general on podman, or the procedure to save and restore the container from docker to podman?

**Comment by nPHYN1T3** [comment] 2022-09-16 09:15
Ah I get what you mean, I never had anything to save or restore. I just tried distrobox with podman.

**Comment by 89luca89** [comment] 2022-09-16 09:39
I've reverted the commit that caused this, thanks to all of you guys for helping debugging this!

**Closed** 2022-09-16 09:39 UTC
Labels: bug

**Comment by tjssoldier** [comment] 2022-09-16 20:41
I tested with the reverted commit and is working like before. Many thanks! Distrobox it's amazing!

**Comment by nPHYN1T3** [comment] 2022-09-16 21:16
Tested new build and yeah it works but sadly it doesn't work for what I had wanted to use it for (Ubu/RH only piece of garbo software).

**Comment by 89luca89** [comment] 2022-09-16 21:21
Which software is it? I'm curious 🤔

**Comment by nPHYN1T3** [comment] 2022-09-16 21:24
Deep breath...UNITY. Game I play the modding tools are just Unity project files. Unity has broken ability to run on anything but Fedora or Ubuntu.

**Comment by 89luca89** [comment] 2022-09-16 21:27
Mmmh i suspect maybe it's missing some dependency

What I saw is that lot of the times software is packaged in an incomplete manner, many deps are assumed which can be OK on a 2gb system, much less on a 35mb one...

**Comment by nPHYN1T3** [comment] 2022-09-16 21:34
Yeah, which I'd also wager if I knew what was missing I could re-jerry-rig it to run on Arch again but you can't figure out the missing so easily. Perhaps with an insane amount of strace time and headache. UnityHub (is garbage) is an electron app and gives no feedback on anything to debug with.

Having said that when I tried this with straight docker I had to manually add a lot but with distrobox it pulled dependencies with the normal Unity install. Comically even the last while when it was "supported" on my platform I'd have to do some jerry rigging to get it to run as it's just a garbage slap-together joke of an application. Just kills me that Valve comes and and says Develop for Arch (SteamDeck) then Unity goes and nukes it on anything but Fedora and Ubuntu. Unity = S M R T -Homer Simpson.

**Comment by 89luca89** [comment] 2022-09-16 21:41
Yea can be frustrating 

Well hope you have a speedy recovery!

**Comment by peterurbanec** [comment] 2022-09-17 15:07
@89luca89 I just wanted to say thank you for all your work on this, the speedy responses to issues and the prompt fix to get us all working again. Your efforts are very much appreciated. :1st_place_medal:
