### ISSUE TITLE
[Error] First container run hangs

### ISSUE THREAD

**Issue by bmacphail** [89luca89/distrobox#1530] opened 2024-08-24 07:24 UTC
An issue was previously closed about this, but the issue appears to have regressed: https://github.com/89luca89/distrobox/issues/1382

**Describe the bug**
Distrobox enter hangs. Upon using Ctrl-C to cancel, the following error is returned:

`/usr/bin/distrobox-enter: line 680: /home/<user>/.cache/distrobox/.ubuntu-20-04.fifo: No such file or directory`

**To Reproduce**
1. Create a new Fedora 40 container in an openSUSE Tumbleweed host (in my case), and attempt to enter it. Using distrobox version 1.7.2.1-11 from the distro repo.

**Expected behavior**
The container runs.

The fix I was able to implement on my system is the same as in the issue linked above: modify line 624 of distrobox-enter to the following:

`log_timestamp="$(date +%FT%TZ)"`

Creating this issue so that the problem gets tracked and fixed.

**Comment by tifasoftware** [comment] 2024-09-20 22:49
I am also having this issue

**Comment by tifasoftware** [comment] 2024-09-20 22:51
That hot-fix also fixed the issue too. I will fork this and start a PR.

**Comment by tifasoftware** [comment] 2024-09-20 22:58
I tested distrobox-git on AUR, and it looks like the issue's been fixed.

**Comment by 89luca89** [comment] 2024-10-12 11:11
Hi @bmacphail I need more context for this
Docker or podman?

I'm not able to reproduce your issue with either of those, on TW, Fedora and Ubuntu hosts

**Comment by TacoCake** [comment] 2024-10-12 12:00
> Hi @bmacphail I need more context for this Docker or podman?
> 
> I'm not able to reproduce your issue with either of those, on TW, Fedora and Ubuntu hosts

For me it's happening with Docker.

Though I have not tried to compile it from source, @tifasoftware says it's fixed already. Perhaps it's time for a new release?

**Comment by 89luca89** [comment] 2024-10-12 12:46
Probably yes! There will be one soon

**Comment by 89luca89** [comment] 2024-10-12 12:46
Can you try with the git version so I can be sure this is fixed?

**Comment by TacoCake** [comment] 2024-10-12 12:54
> Can you try with the git version so I can be sure this is fixed?

Just tried the latest commit, works correctly without hanging 🎉

**Comment by 89luca89** [comment] 2024-10-12 13:13
Perfect! Closing this, the new release will be following soon :tada:

**Closed by 89luca89** 2024-10-12 13:13 UTC
Labels: bug, help wanted, good first issue, wait-on-user

**Comment by jpf91** [comment] 2025-04-16 13:40
Still seeing this (`Starting container...` never finishing) on 1.8.1.2 on RHEL 9.5 with podman 5.2.2. Any idea how to debug this further or how to workaround it?
