### ISSUE TITLE
[Error] `distrobox enter` on Void Linux musl fails.

### ISSUE THREAD

**Issue by computerscience-person** [89luca89/distrobox#1436] opened 2024-06-12 07:10 UTC
**Describe the bug**
Void Linux (musl version) fails to enter with `distrobox enter`

**To Reproduce**
`distrobox ephemeral --image ghcr.io/void-linux/void-musl-full:latest --verbose

**Expected behavior**
Enter a Void Linux environment

**Logs**

```
---snip---
ERROR: runit-void-20231124_5: [unpack] failed to unpack files from archive: Invalid argument
...
runit-void-20231124_4: updating to 20231124_5 ...
runit-void-20231124_5: unpacking ...
...
Error: An error occurred
DEBU[0000] Called logs.PersistentPostRunE(/run/current-system/sw/bin/podman --log-level debug logs distrobox-aSZXGcm5sa)
DEBU[0000] Shutting down engines
---snip---
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 5.1.1
 - Which version of distrobox? 1.7.2.1
 - Which host distribution? NixOS
 - How did you install distrobox? System package

**Additional context**

**Comment by 89luca89** [comment] 2024-06-19 13:23
Duplicate of #1380

**Closed by 89luca89** 2024-06-19 13:23 UTC
Labels: bug
