### ISSUE TITLE
[Error] GUI apps with .sh shell script not worked on SteamOS

### ISSUE THREAD

**Issue by dtantono** [89luca89/distrobox#624] opened 2023-02-14 09:37 UTC
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
I tested the script with ./Gedit.sh on Konsole and it works well. But on Dolphin it does not worked and also I tried with multiple applications as well. Strangely, when I typed dolphin on Konsole and double click the app on dolphin or drag the script to Konsole. it works again 

**To Reproduce**
1. cd /home/user/Downloads/
2. chmod u+x Gedit.sh
3. right click on the app on Dolphin
4. Click Permission
5. Allow the file to run as a program
6. click ok
7. double click it and it does not start

**Expected behavior**
it should works on normal occasion without resorting on Terminal. 

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

**Desktop (please complete the following information):**
Are you using podman or docker? Podman 3.4.4
Which version or podman or docker?3.4.4
Which version of distrobox? 1.4.2.1

**Additional context**
I don't know is this bug specific to SteamOS but, the  I tested the script with different applications on another Ubuntu PC and the script works fine and repeat the same method and it works well 
What do you think?

[Gedit.sh.zip](https://github.com/89luca89/distrobox/files/10730710/Gedit.sh.zip)

**Comment by 89luca89** [comment] 2023-02-25 09:02
Hi @dtantono I think this is a duplicate of #463 
You should be able to fix it using this fix:

> Add export PATH=$HOME/.local/bin:$HOME/.local/podman/bin:$PATH
at the end of /etc/profile.

**Closed by 89luca89** 2023-02-25 09:02 UTC
Labels: bug

**Comment by dtantono** [comment] 2023-02-25 14:59
@89luca89 I tried that workaround and it does not worked.
