### ISSUE TITLE
Arch Distrobox bricking itself on NixOS and won't compile Cargo packages [Error]

### ISSUE THREAD

**Issue by nonetrix** [89luca89/distrobox#1353] opened 2024-04-22 21:08 UTC
**Describe the bug**
A update to what I assume is either being caused by `binutils` or `glibc` is making it such that my containers are bricking themselves after upgrading using `pacman -Syu`. I first noticed something fishy when I created a new container for running Rust projects named `programming` and it would not compile any package but just output the following when running `cargo run` on the default project:
```
📦[noah@programming]~/Documents/Projects/rust/testing% cargo run
   Compiling testing v0.1.0 (/home/noah/Documents/Projects/rust/testing)
error: linking with `cc` failed: signal: 8 (SIGFPE) (core dumped)
  |
  = note: LC_ALL="C" PATH="/usr/lib64/rustlib/x86_64-unknown-linux-gnu/bin:/nix/store/h1j6h0nq1qqc7h0r4i8f8a6w1yad00si-zplug-2.4.2/share/zplug/bin:/home/noah/.zplug/bin:/home/noah/.local/bin:/nix/store/d03vq9y80w0vkmd9c37jf3zigr8s4v5p-kitty-0.33.1/bin:/nix/store/32hx7y3vn8l5wvpzw7jgradnxnlsb6y2-imagemagick-7.1.1-29/bin:/nix/store/2nhjsfc4pg74vqnsbjmnpi7359y6f3wi-ncurses-6.4-dev/bin:/run/wrappers/bin:/home/noah/.nix-profile/bin:/nix/profile/bin:/home/noah/.local/state/nix/profile/bin:/etc/profiles/per-user/noah/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/bd0ii4p72zgiy1jfaww5h3xihxn2l56x-gcc-wrapper-13.2.0/bin:/nix/store/jsjfmx7r6cpyixxsg7bjl5cy3y8hw7k7-binutils-wrapper-2.41/bin:/nix/store/pc6yqwmnzy0xqdzm7j9kxhl0hrmk4p50-pciutils-3.11.1/bin:/nix/store/5zw6k903flzjrp3yiqrm5isvdfq30y3l-pkgconf-wrapper-2.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-m64" "/tmp/rustc8yevpb/symbols.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.1ufsu3sxam81197m.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.1vc1vkxj3n8m2b7d.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.1xou637uvvh72nzh.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.2i8gu9pq4vkkq3iw.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.2nr3zxd798bvmy68.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.eokah44cfkn4ckr.rcgu.o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1.1ej71lsvujle4n98.rcgu.o" "-Wl,--as-needed" "-L" "/home/noah/Documents/Projects/rust/testing/target/debug/deps" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-434b320583c9243e.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-2bb6e80cb2931b65.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libobject-f88ed0ddcb9655b2.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-5d123efd8ce975c4.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-eb7917304bae0773.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-485ecf22f295bd66.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-03befa562f06203c.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-cbf3fe64ade8a4dd.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-d6f316f58d86f2e7.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-eab04b16c48e8d17.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-475adb5ad370cedd.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libadler-0befc8acc36b7b34.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-8a1cb817e9c15512.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-5608eee63b1e6326.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-c438dc4fba216746.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-4a1a859cfb6d4f23.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-5aa7eee7031c9fcc.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcore-0ab56e5300936d4a.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-54db803ece53f837.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/noah/Documents/Projects/rust/testing/target/debug/deps/testing-994c21aea6562fc1" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: 

error: could not compile `testing` (bin "testing") due to 1 previous error
```
After trying to reinstall some packages my terminal will just freeze not even letting me press <kbd>^C</kbd> only closing works and which after the container cannot be entered and will just output the following, I also tried upgrading my container `ai` and after upgrading I got the same result. I assumed it had to do with `binutils`, `gcc`, or `glibc` however, for some reason reproducing this seems somewhat random:
https://gist.github.com/nonetrix/b84f8b5094393f01d3ad8da18a63ff7d

**To Reproduce**
1. Make new container
2. Install Rust and basic dev dependencies
3. ???
4. It bricks itself for no reason

**Expected behavior**
The container compiles Rust programs without issue and upgrades not bricking it

**Logs**
Run the commands with `--verbose` and post the log here as a file upload:
https://gist.github.com/nonetrix/e5bf8883dd9a4da5d61c96f4c8b79470

Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag:
These commands don't seem to work
```
❯ docker logs
"docker logs" requires exactly 1 argument.
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container

~ 
❯ docker logs --latest
unknown flag: --latest
See 'docker logs --help'.

~ 
❯ docker logs --latest
unknown flag: --latest
See 'docker logs --help'.

~ 
❯ docker logs --latest --verbose
unknown flag: --latest
See 'docker logs --help'.
```

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - Which version or podman, docker or lilipod?
 - Which version of distrobox?
 - Which host distribution?
 - How did you install distrobox?

**Additional context**
```
♥ ❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.8.5, NixOS, 24.05 (Uakari), 24.05.20240412.cfd6b5f`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.2`
 - channels(root): `"home-manager, nixos"`
 - nixpkgs: `/nix/store/yy5l09gfsagkv8rswblknmsjc2gyr20d-source` 
```
My system configs: https://github.com/nonetrix/nixdots
Image used: docker.io/library/archlinux:latest

In general I have had lots of strange issues with Distrobox on Nix, seems to be due to how Nix handles the file system a lot differently and it seriously needs to be worked on in my opinion in general because this isn't the only issue I have had before

**Comment by postsolar** [comment] 2024-04-25 12:45
I've also had an issue possibly related to `glibc` on NixOS recently.

```
 $  distrobox-create --name arch2 --additional-flags "--device nvidia.com/gpu=all --security-opt=label=disable -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all" --image archlinux:latest
Creating 'arch2' using image archlinux:latest	[ OK ]
Distrobox 'arch2' successfully created.
To enter, run:

distrobox enter arch2


 $  distrobox-enter arch2
 Error: could not start entrypoint.
+ stat /run/host/etc/shadow
stat: symbol lookup error: /nix/store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE
+ '[' -n '' ']'
+ printf 'distrobox: Installing basic packages...\n'
distrobox: Installing basic packages...
++ basename fish
basename: symbol lookup error: /nix/store/35pq4hr29c3sl79lgfwgsvd9nwzyp4am-glibc-2.39-5/lib/libc.so.6: undefined symbol: __tunable_is_initialized, version GLIBC_PRIVATE
+ shell_pkg=
+ '[' 127 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
```

I got it fixed by dropping everything related to nvidia from the `distrobox create` command, as my nvidia card seems to be working anyways thanks to [virtualisation.containers.cdi.dynamic.nvidia.enable](https://search.nixos.org/options?channel=unstable&show=virtualisation.containers.cdi.dynamic.nvidia.enable&from=0&size=50&sort=relevance&type=packages&query=virtualisation.containers.cdi.dynamic.nvidia.enable) NixOS option. But building a Rust package is still not possible:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/me/.cargo/bin:/run/wrappers/bin:/home/me/.local/bin:/home/me/.nix-profile/bin:/home/me/.local/state/nix/profile/bin:/home/me/.local/state/nix/profile/bin:/etc/profiles/per-user/me/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin:/nix/store/bd0ii4p72zgiy1jfaww5h3xihxn2l56x-gcc-wrapper-13.2.0/bin:/nix/store/jsjfmx7r6cpyixxsg7bjl5cy3y8hw7k7-binutils-wrapper-2.41/bin:/nix/store/pc6yqwmnzy0xqdzm7j9kxhl0hrmk4p50-pciutils-3.11.1/bin:/nix/store/5zw6k903flzjrp3yiqrm5isvdfq30y3l-pkgconf-wrapper-2.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl" VSLANG="1033" "cc" "-m64" "/tmp/rustcHlhWnV/symbols.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.24m7yg6y4t03xyi5.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.26p2wt9ndrlkk2cq.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.3sbghcx5hzug2wjr.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.47mb2bqv2nmmywn7.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.49qi3z69b1mesnp0.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.5e73xe5ez4ba1eli.rcgu.o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e.3fqzg72l5lomdf2i.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/treeman/target/debug/deps" "-L" "/tmp/treeman/target/debug/build/tree-sitter-f328a836678521c6/out" "-L" "/tmp/treeman/target/debug/build/curl-sys-1772e6ec3cbf425a/out/build" "-L" "/tmp/treeman/target/debug/build/libnghttp2-sys-db615a03ea787a81/out/i/lib" "-L" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/treeman/target/debug/deps/libshared-6087cc8ceed232be.rlib" "/tmp/treeman/target/debug/deps/liblsp_types-c35d2fd8d128e07e.rlib" "/tmp/treeman/target/debug/deps/libbitflags-95901817437ee887.rlib" "/tmp/treeman/target/debug/deps/libisahc-12afe95780fa7466.rlib" "/tmp/treeman/target/debug/deps/libmime-63c3a22c1367bd96.rlib" "/tmp/treeman/target/debug/deps/libcastaway-296c133232b4e34c.rlib" "/tmp/treeman/target/debug/deps/libencoding_rs-7c4d9852fb2bab44.rlib" "/tmp/treeman/target/debug/deps/libtracing_futures-4a7da1c12987b41f.rlib" "/tmp/treeman/target/debug/deps/libtracing-02126eab4492c92d.rlib" "/tmp/treeman/target/debug/deps/libtracing_core-6a2bb6c7587e86fa.rlib" "/tmp/treeman/target/debug/deps/libpin_project-dd75262c8d74e6a1.rlib" "/tmp/treeman/target/debug/deps/libhttp-ccd7395bbd209ccf.rlib" "/tmp/treeman/target/debug/deps/libbytes-ceb051219b0bb2e3.rlib" "/tmp/treeman/target/debug/deps/libfnv-1e0f89410295e7ee.rlib" "/tmp/treeman/target/debug/deps/libsluice-0eb88a9d3f01c8db.rlib" "/tmp/treeman/target/debug/deps/libpolling-a9ee839b7d89fccf.rlib" "/tmp/treeman/target/debug/deps/libslab-d903803c5983889b.rlib" "/tmp/treeman/target/debug/deps/libfutures_lite-92f7503440f07b72.rlib" "/tmp/treeman/target/debug/deps/libfastrand-e76bfc963f15880c.rlib" "/tmp/treeman/target/debug/deps/libfutures_io-e09306559c50b5cd.rlib" "/tmp/treeman/target/debug/deps/libwaker_fn-04efb904e151c44d.rlib" "/tmp/treeman/target/debug/deps/libparking-dbe143e8541b795f.rlib" "/tmp/treeman/target/debug/deps/libpin_project_lite-6814510c287d86b3.rlib" "/tmp/treeman/target/debug/deps/libcurl-44d3a4cf04a6026e.rlib" "/tmp/treeman/target/debug/deps/libopenssl_probe-c6c2d4b7b350ab73.rlib" "/tmp/treeman/target/debug/deps/libsocket2-437a3c4d53731d23.rlib" "/tmp/treeman/target/debug/deps/libcurl_sys-cd9f5be026063590.rlib" "/tmp/treeman/target/debug/deps/libopenssl_sys-465d1ac8719e3f0a.rlib" "/tmp/treeman/target/debug/deps/liblibz_sys-ec7dee851449b83e.rlib" "/tmp/treeman/target/debug/deps/liblibnghttp2_sys-180d8036d4d14330.rlib" "/tmp/treeman/target/debug/deps/libasync_channel-6b5a2644a1faceb6.rlib" "/tmp/treeman/target/debug/deps/libfutures_core-44482a57f3cfc816.rlib" "/tmp/treeman/target/debug/deps/libevent_listener-e85b00f9f6a91552.rlib" "/tmp/treeman/target/debug/deps/libconcurrent_queue-fb437a80bcce82ec.rlib" "/tmp/treeman/target/debug/deps/libcrossbeam_utils-ad2fbaa74d2b1dd1.rlib" "/tmp/treeman/target/debug/deps/libserde_json-3041eedb32548a70.rlib" "/tmp/treeman/target/debug/deps/libryu-a999776070da1fc2.rlib" "/tmp/treeman/target/debug/deps/libitoa-fdbe94e95be91cb8.rlib" "/tmp/treeman/target/debug/deps/libgrammar-4d8e9e4307fdb5c6.rlib" "/tmp/treeman/target/debug/deps/libdunce-d983ba0af25c793e.rlib" "/tmp/treeman/target/debug/deps/libonce_cell-a2bf43a16298c395.rlib" "/tmp/treeman/target/debug/deps/libcc-02cdf571782c2a2b.rlib" "/tmp/treeman/target/debug/deps/libjobserver-356e75b8b64b6c0c.rlib" "/tmp/treeman/target/debug/deps/libthreadpool-12d26f52c7e1e7e9.rlib" "/tmp/treeman/target/debug/deps/libnum_cpus-dcd342bdf131cd3f.rlib" "/tmp/treeman/target/debug/deps/libwhich-5c64e557d807b429.rlib" "/tmp/treeman/target/debug/deps/libeither-d6eba6f4a78614c5.rlib" "/tmp/treeman/target/debug/deps/liblog-15e6f56c78050c1f.rlib" "/tmp/treeman/target/debug/deps/libdirectories-eb8d040446cc1706.rlib" "/tmp/treeman/target/debug/deps/libdirs_sys-7045cd2e984e37cd.rlib" "/tmp/treeman/target/debug/deps/liblibc-a43a59a5d8ec5411.rlib" "/tmp/treeman/target/debug/deps/liboption_ext-f930da6ba8a267b4.rlib" "/tmp/treeman/target/debug/deps/libetcetera-2fc3c2268190a68f.rlib" "/tmp/treeman/target/debug/deps/libhome-7553557a1b0f12c1.rlib" "/tmp/treeman/target/debug/deps/liblibloading-3fe5bc498692e92e.rlib" "/tmp/treeman/target/debug/deps/libtree_sitter-89c4cf7e3db9ac19.rlib" "/tmp/treeman/target/debug/deps/libregex-ee87b9ffc896fcfe.rlib" "/tmp/treeman/target/debug/deps/libregex_automata-10acb60e6afbf76d.rlib" "/tmp/treeman/target/debug/deps/libaho_corasick-93042598ab0ded68.rlib" "/tmp/treeman/target/debug/deps/libmemchr-246a68bdedd80b25.rlib" "/tmp/treeman/target/debug/deps/libregex_syntax-85d72156c4dd07c3.rlib" "/tmp/treeman/target/debug/deps/libtempfile-662cb4046052bb87.rlib" "/tmp/treeman/target/debug/deps/libfastrand-42c9061e7cf4af12.rlib" "/tmp/treeman/target/debug/deps/librustix-68d227f7069f15ba.rlib" "/tmp/treeman/target/debug/deps/libbitflags-3237b3468ac872fb.rlib" "/tmp/treeman/target/debug/deps/liblinux_raw_sys-90f1ebdedbac8b8f.rlib" "/tmp/treeman/target/debug/deps/libcfg_if-3705568b3b302f3c.rlib" "/tmp/treeman/target/debug/deps/libanyhow-1d7657fade43be4f.rlib" "/tmp/treeman/target/debug/deps/liburl-a2eb4b347c7d3e88.rlib" "/tmp/treeman/target/debug/deps/libidna-fb778f2339b4fb56.rlib" "/tmp/treeman/target/debug/deps/libunicode_normalization-061d8583de547e06.rlib" "/tmp/treeman/target/debug/deps/libtinyvec-abd340c833b1280d.rlib" "/tmp/treeman/target/debug/deps/libtinyvec_macros-4d1f585150a22e8a.rlib" "/tmp/treeman/target/debug/deps/libunicode_bidi-acae8c4c7af83b2d.rlib" "/tmp/treeman/target/debug/deps/libform_urlencoded-dd32b0e9e547eda4.rlib" "/tmp/treeman/target/debug/deps/libpercent_encoding-2d22a78c7ad4c2e3.rlib" "/tmp/treeman/target/debug/deps/libserde-810e5ab51b98daae.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-2d08990d644ac786.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6f2d4ec7ff80253d.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libobject-c194d68892442324.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libmemchr-9a71c52c5946f83b.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-ae9aec4ce2dabc4f.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-6a207457d27610cc.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-fb1d2514710eef16.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-e36e7ed4b08caeac.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-9e8dafdf0a1b7ecd.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-b218f37fe3c9ce2e.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-20c30954fd9b5ef4.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libadler-6d3dfaf536d51163.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-cb4ce50789112af8.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-9897980a3b548e05.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-b7bd4d010c784af2.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-6d4515df28ba3369.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-e28568c1a21499f7.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-eedf3675950a13c2.rlib" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-715e69127681e2e0.rlib" "-Wl,-Bdynamic" "-lssl" "-lcrypto" "-lz" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/me/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/treeman/target/debug/build/tim-79b82f9f703f928e/build_script_build-79b82f9f703f928e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-nodefaultlibs"
  = note: /nix/store/hqvni28zpibl6jsqqimcvng6h6qm58xy-binutils-2.41/bin/ld: cannot find -lssl: No such file or directory
          /nix/store/hqvni28zpibl6jsqqimcvng6h6qm58xy-binutils-2.41/bin/ld: cannot find -lcrypto: No such file or directory
          /nix/store/hqvni28zpibl6jsqqimcvng6h6qm58xy-binutils-2.41/bin/ld: cannot find -lz: No such file or directory
          collect2: error: ld returned 1 exit status
          

error: could not compile `tim` (build script) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by nonetrix** [comment] 2024-04-25 21:28
Well I am using a AMD GPU in my case

**Comment by 89luca89** [comment] 2024-06-19 15:24
Seems like a PATH issue
can you try senting just the `podman logs name-of-container` before and after the brick, with a new container?

Right now the logs are so huge it's impossible to infere much
thanks!

**Comment by nonetrix** [comment] 2024-06-19 17:34
I haven't had issue in a while, it likes to come and go unfortunately I'll see if I can reproduce

**Comment by 89luca89** [comment] 2024-06-19 19:38
Thanks @nonetrix 
in this case I'll close this and if you manage to reproduce we can reopen

**Closed by 89luca89** 2024-06-19 19:38 UTC
Labels: bug, wait-on-user
