### ISSUE TITLE
[Error] Container cannot find shell after reboot

### ISSUE THREAD

**Issue by Bloodsnake** [89luca89/distrobox#695] opened 2023-04-08 00:37 UTC
**Describe the bug**

I have a host system with EndeavourOS and the fish shell as the default shell and I want to create a new debian container. After the container got created and I execute neofetch the line that lists the shell gets corrupted with the message: "/bin/fish: No such file or directory". This is already a sign that something went wrong but everything else still works normally. I can enter and exit the container normally. Only after I then reboot the host system and try to enter the container again it throws an error: "/bin/fish: not found". This error can only get avoided when I install fish in the container and move the executable manually to /bin/fish. This isn't the case with any other distro inside the container I have tried (Fedora, Ubuntu).

**To Reproduce**

Have a EndeavourOS system with fish as your default shell

- Create a new debian container ``distrobox create --image debian --name test``
- Enter the container  ``distrobox enter test ``
- Exit the container  ``exit ``
- Reboot the host system
- Enter the container again ``distrobox enter test ``
- Now the container throws an error

**Expected behavior**
The container should start normally after the reboot of the host
[logs.txt](https://github.com/89luca89/distrobox/files/11182194/logs.txt)

**Comment by misobarisic** [comment] 2023-04-08 13:19
For me it says `fish /usr/bin/neofetch: line 1669: /bin/fish: No such file or directory` under shell in neofetch but I haven't had problems with it throwing errors on subsequent startups.

**Comment by Bloodsnake** [comment] 2023-04-08 13:24
Yes that's the full error, I shorted it a bit in my original post.

**Comment by Bloodsnake** [comment] 2023-04-08 17:28
I found a workaround for the problem. Changing my shell with ``chsh`` to ``/usr/bin/fish`` on the host seems to fix the problem. My guess is that apt doesn't create a symlink in ``/bin/fish`` inside the debian container when installing fish. I'm not sure if I should mark this issue as closed since normally distrobox should fallback to bash when problems like this occur so I'll just keep it open for now.

**Comment by misobarisic** [comment] 2023-04-08 18:05
I've previously had similar issues since my host machine has /bin symlinked to /usr/bin whereas Debian does not. Should have been fixed in #442.

**Comment by misobarisic** [comment] 2023-04-08 18:07
What version of distrobox are you using?

**Comment by Bloodsnake** [comment] 2023-04-08 23:52
``distrobox --version`` returns: ``distrobox: 1.4.2.1`` which should be the latest version in the arch community repository.

**Comment by 89luca89** [comment] 2023-04-09 08:34
By default, if you don't pass a command to enter, it just tries to use the shell in `/etc/passwd` of the container
Now, in there, the shell is set based on the output of `command -v` 

It seems like during the init, it worked as `/bin/fish` but then it wasn't really there?

**Comment by misobarisic** [comment] 2023-04-09 08:58
Container's `$SHELL` variable does not get set to `/usr/bin/fish`. Could that be the source of the issue?

**Comment by misobarisic** [comment] 2023-04-09 09:02
Creating a box while also passing `--additional-flags "--env SHELL=/usr/bin/fish"` does not cause `fish /usr/bin/neofetch: line 1669: /bin/fish: No such file or directory` to appear in neofetch.

**Comment by Bloodsnake** [comment] 2023-04-09 14:29
Yes, creating the box with the  ``--additional-flags "--env SHELL=/usr/bin/fish"`` argument seems to fix the issue for me too.

**Comment by misobarisic** [comment] 2023-04-09 14:57
I suppose this [line](https://github.com/89luca89/distrobox/blob/main/distrobox-init#L827) sets `$SHELL` on first startup.

**Comment by 89luca89** [comment] 2023-08-05 12:15
Is this still reproducible? I cannot reproduce it myself

**Comment by 89luca89** [comment] 2023-08-11 17:34
I cannot reproduce using latest version and a debian11 image

Right now the init will detect the PATH of the SHELL and set it for the user inside (so /usr/bin or /bin is not a problem)
Then the enter will detect the shell from the passwd file, so it should start the shell with the correct path in the container

And it seems to work with newly created containers with debian11 for me

**Closed** 2023-08-13 12:53 UTC
Labels: bug
