### ISSUE TITLE
[Error] Can't enter container with nvidia integration on some Ubuntu systems

### ISSUE THREAD

**Issue by Meister1593** [89luca89/distrobox#1095] opened 2023-12-10 15:12 UTC
Hello!
I'm maintainer of https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide project and seems like multiple people started to get this issue on Ubuntu 22.04, Pop!_OS 22.04. 
Related issue: https://github.com/alvr-org/ALVR-Distrobox-Linux-Guide/issues/13

**Describe the bug**
When trying to enter container with `--nvidia` integration, it fails to do so with `mkdir: cannot create directory ‘/usr/lib64/nvidia/xorg’: Read-only file system` error

**To Reproduce**
Have nvidia gpu.
Possibly ubuntu 22.04 or Pop!_OS 22.04 (unknown if it's the main cause)
```bash
mkdir test-nvidia
cd test-nvidia
wget -O podman https://github.com/89luca89/podman-launcher/releases/download/v0.0.3/podman-launcher-amd64
chmod +x podman
mkdir -p "$HOME/.local/bin"
mv podman "$HOME/.local/bin"
git clone https://github.com/89luca89/distrobox.git distrobox
cd distrobox
mkdir -p "$HOME/.local/bin"
./install
cd ..
export PATH="$HOME/.local/bin:$PATH"
distrobox-create --verbose --image docker.io/library/archlinux:latest --name test-nvidia --home ~/test-nvidia/test-nvidia --nvidia 2>&1 | tee ~/test-nvidia/distrobox-create.log
distrobox-enter --verbose --name test-nvidia 2>&1 | tee ~/test-nvidia/distrobox-enter.log
```

**Expected behavior**
It should enter normally, without errors and work with gpu.

**Logs**
[distrobox-create.log](https://github.com/89luca89/distrobox/files/13628214/distrobox-create.log)
[distrobox-enter.log](https://github.com/89luca89/distrobox/files/13628212/distrobox-enter.log)

**Desktop (please complete the following information):**
 - Podman
 - podman-launcher v0.0.3
 - Which version of 1.6.0.1, latest, doesnt matter
 - Ubuntu 22.04, Pop!_OS 22.04
 - Installation through script, to home user.

**Comment by gumorr** [comment] 2024-01-21 23:28
having the same issue with ALVR, issue seems to be the distrobox-init script crapping out while copying all the nvidia libraries to the container

logs from podman:
```
+ for nvidia_lib in ${NVIDIA_LIBS}
++ printf %s /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
++ sed 's|/run/host/usr/lib/x86_64-linux-gnu/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib/i386-linux-gnu/|/usr/lib/|g'
++ sed 's|/run/host/usr/lib64/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib32/|/usr/lib/|g'
+ dest_file=/usr/lib64/nvidia/current/libnvidia-ml.so
+ '[' -e /usr/lib64/nvidia/current/libnvidia-ml.so ']'
+ type=file
+ '[' -L /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so ']'
+ type=link
+ '[' link = link ']'
++ dirname /usr/lib64/nvidia/current/libnvidia-ml.so
+ mkdir -p /usr/lib64/nvidia/current
+ cp -d /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so /usr/lib64/nvidia/current/libnvidia-ml.so
cp: cannot create symbolic link '/usr/lib64/nvidia/current/libnvidia-ml.so': Read-only file system
+ '[' 1 -ne 0 ']'
Error: An error occurred
+ printf 'Error: An error occurred\n'
```
the exact bit of code that's the issue is right here: https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-init#L1539-L1575

**Comment by 89luca89** [comment] 2024-02-19 21:32
This has been fixed in latest git commits :+1:

**Closed by 89luca89** 2024-02-19 21:32 UTC
Labels: bug

**Comment by pathquester** [comment] 2024-02-25 03:31
@89luca89 I have tried with the latest git version and I am getting:

+ for nvidia_lib in ${NVIDIA_LIBS}
++ printf %s /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
++ sed 's|/run/host/usr/lib/x86_64-linux-gnu/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib/i386-linux-gnu/|/usr/lib/|g'
++ sed 's|/run/host/usr/lib64/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib32/|/usr/lib/|g'
+ dest_file=/usr/lib64/nvidia/current/libnvidia-ml.so
+ '[' -e /usr/lib64/nvidia/current/libnvidia-ml.so ']'
+ type=file
+ '[' -L /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so ']'
+ type=link
+ '[' link = link ']'
++ dirname /usr/lib64/nvidia/current/libnvidia-ml.so
+ mkdir -p /usr/lib64/nvidia/current
++ md5sum /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
++ cut -d ' ' -f 1
++ md5sum /usr/lib64/nvidia/current/libnvidia-ml.so
++ cut -d ' ' -f 1
md5sum: /usr/lib64/nvidia/current/libnvidia-ml.so: No such file or directory
+ '[' 22134eda86c6cbae169a486b72599aa1 '!=' '' ']'
+ cp -d /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so /usr/lib64/nvidia/current/libnvidia-ml.so
cp: cannot create symbolic link '/usr/lib64/nvidia/current/libnvidia-ml.so': Read-only file system
+ '[' 1 -ne 0 ']'
+ printf 'Error: An error occurred\n'
Error: An error occurred
DEBU[0003] Called logs.PersistentPostRunE(podman --log-level debug logs arch-nvidia) 

It was created with distrobox create --nvidia --name arch-nvidia --image docker.io/library/archlinux:latest on Debian bookworm.
