### ISSUE TITLE
Cannot open debian distrobox due to tzdata issue

### ISSUE THREAD

**Issue by john-ghatas** [89luca89/distrobox#715] opened 2023-04-22 14:32 UTC
Might be a regression, but when tzdata needed an update it threw up [x has stale file handle] and after a reboot re entering the distrobox showed the following error in the logs.

```
The following packages will be upgraded:
  tzdata
1 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
35 not fully installed or removed.
Need to get 301 kB of archives.
After this operation, 6144 B of additional disk space will be used.
Get:1 http://http.us.debian.org/debian unstable/main amd64 tzdata all 2023c-3 [301 kB]
Preconfiguring packages ...
Fetched 301 kB in 1s (440 kB/s)
(Reading database ... 304168 files and directories currently installed.)
Preparing to unpack .../tzdata_2023c-3_all.deb ...
Unpacking tzdata (2023c-3) over (2023c-2) ...
dpkg: error processing archive /var/cache/apt/archives/tzdata_2023c-3_all.deb (--unpack):
 unable to make backup link of './usr/share/zoneinfo/Etc/UTC' before installing new version: Invalid cross-device link
```

**Comment by 89luca89** [comment] 2023-05-02 20:37
Hi @john-ghatas 
I'm not able to reproduce this, please can you give more info on how to reproduce this issue? Thanks

**Comment by john-ghatas** [comment] 2023-05-02 21:33
- Create a box with an older image
```
distrobox create -i debian:unstable-20221004 -n debian-test
```
- Enter the box
- Add the non-free repos etc
```
echo "deb http://http.us.debian.org/debian unstable main contrib non-free non-free-firmware" | sudo tee -a /etc/apt/sources.list
```
- Run an update on tzdata
```
sudo apt --only-upgrade install tzdata
```

You should see output like this:
![image](https://user-images.githubusercontent.com/14125058/235790993-ef889a36-806a-4cb6-9352-d866dbc6ac19.png)


Without adding the extra repos the updates run just fine

**Comment by john-ghatas** [comment] 2023-05-03 11:38
I tried the same with an ubuntu container, this issue seems to be present.

**Comment by starquake** [comment] 2023-05-04 13:19
I have the same issue with updating a debian distrobox. Steps to reproduce:

- `distrobox create -i debian:11 -n issue-715`
- `distrobox enter issue-715`
inside the distrobox run: 
- `sudo apt-get update`
- `sudo apt-get upgrade`

It will try to upgrade tzdata and fail.

As a temporary workaround i'm skipping updating tzdata:
`sudo apt-mark hold tzdata`

**Comment by frasertajima** [comment] 2023-05-04 17:42
thank you starquake for:

`sudo apt-mark hold tzdata`

I can finally get back to installing pytorch, tensorflow and tensorflowRT on Fedora Silverblue 38 (by the way, distrobox was not installed on a clean re-install of FS 38).

**Comment by john-ghatas** [comment] 2023-06-04 17:51
Not an issue here, have you enabled any third party repo that might be causing this?

**Comment by tazihad** [comment] 2023-06-04 18:11
@john-ghatas distrobox: 1.4.2.1
this is the command trying to install ubuntu-22-04
```
distrobox create --name ubuntu-22-04 --image quay.io/toolbx-images/ubuntu-toolbox:22.04 --home /var/home/yol1/distrobox/ubuntu-22-04
```
that's pretty much it. I can't apt update. As it shows same error as you.

**Comment by john-ghatas** [comment] 2023-06-04 18:26
Did you install distrobox from the repos of your distro or are you running the git version

**Comment by john-ghatas** [comment] 2023-06-06 16:03
Small update, seeing the issue on the latest distrobox git version as well. For how I've held the package back

```
dpkg: error processing package tzdata (--remove):
 unable to securely remove '/usr/share/zoneinfo/Etc/UTC': Device or resource busy
```

**Comment by 89luca89** [comment] 2023-06-11 17:15
Pushed a potential fix with 1cde681369576d3aca9d68834a053422b65a06a7

Now tzdata is added at the beginning and then mark hold it, we don't need update to this anyway as we sync with host

I'll wait feedbacks before closing this

**Comment by 89luca89** [comment] 2023-06-11 21:31
Fixed the bug, it was not in that commit but this last one finally.

Sadly you will need to recreate the container for it to be effective, as we move the localtime mount from podman to the init

**Closed** 2023-06-11 21:30 UTC
Labels: bug

**Comment by luc14n0** [comment] 2023-06-11 22:35
I can confirm that for newly created containers the issue is gone, APT doesn't try to update it anymore. For people not willing to recreate the container, they can circumvent the issue by adding something like this in their shell profile config file:

``` sh
test "${CONTAINER_ID}" = "MY_CONTAINER_NAME" && sudo apt-mark hold tzdata
```

**Comment by luc14n0** [comment] 2023-06-13 05:55
> Fixed the bug, it was not in that commit but this last one finally.
> 
> Sadly you will need to recreate the container for it to be effective, as we move the localtime mount from podman to the init

Just to be clear on my end. I tested the first commit - well, only the part about `tzdata` -, not the second. My
comment came through before I realized the existence of this one.

**Comment by 89luca89** [comment] 2023-06-13 07:22
Right now this is solved
simply the idea of using hooks to umount/remount the r-o files was ok
problem was, something mounted by podman using `--volume` is really going to stick
so I just moved the mounting to inside the `init` so it's possible do umount/remount clearly and now tzdata update works

**Comment by luc14n0** [comment] 2023-06-15 12:36
That's good to know. Thanks for the fix 👍

**Comment by cheako** [comment] 2024-04-22 04:46
Is this an issue again?
docker.io/library/debian  sid-slim     4a5774115b18  5 weeks ago
