### ISSUE TITLE
[Error] Failure starting container, "chown: changing ownership of '/home/bart/.bash_logout': Operation not permitted"

### ISSUE THREAD

**Issue by PureTryOut** [89luca89/distrobox#227] opened 2022-04-06 09:57 UTC
**Describe the bug**
After creating a container successfully, actually starting it fails on an Alpine Linux edge host due to it trying to change ownership of `.bash_logout` (which does not exist yet on my host at least) but having no permission to do so. However trying again later it failed on making `~/.local/share/themes` instead, again with a permission problem. 

**To Reproduce**
1. Get an Alpine Linux edge system
2. Install distrobox
3. Create a regular container
4. Try and start it

**Expected behavior**
The container to start, obviously

**Logs**
[distrobox-enter.log](https://github.com/89luca89/distrobox/files/8425799/distrobox-enter.log)
[podman.log](https://github.com/89luca89/distrobox/files/8425805/podman.log)

**Desktop (please complete the following information):**
 - OS: Alpine Linux edge
 - Version: Distrobox version 1.2.14

**Comment by 89luca89** [comment] 2022-04-06 10:28
Hi @PureTryOut 
I've just tried Alpine 3.14.3, I'll need to check for Edge
Are you also using docker or podman?

**Comment by PureTryOut** [comment] 2022-04-06 11:18
Podman, configured to run rootless

**Comment by PureTryOut** [comment] 2022-04-12 16:21
I've just tried it on a different machine (also Alpine Linux edge) and it fails differently there.

```
$ distrobox enter
Starting container fedora-toolbox-35
run this command to follow along:
        podman logs -f fedora-toolbox-35
..........................................
done!
Error: OCI runtime error: crun: open executable: Not a directory

An error occurred

An error occurred
```

**Comment by 89luca89** [comment] 2022-04-18 20:10
Hi @PureTryOut 

These days I've tried with 
3.14.6
3.15.4
edge

Both podman and docker, and I could not reproduce the issue you have, the first one and expecially the second one suggest me that there might be some problems with podman setup
Bear in mind I just limited myself to `apk add podman` and use it normally, no changes made to the configuration and all of the versions worked as intended :shrug:

**Comment by PureTryOut** [comment] 2022-04-23 14:27
I made no changes to podman other than what is suggested on https://wiki.alpinelinux.org/wiki/Podman to get it working rootless. I cleared out all images and I still get the last error, even though I can run other podman images (without distrobox) perfectly fine rootless.

**Comment by awsomearvinder** [comment] 2022-04-25 10:13
I'm on NixOS and I had a similar issue. My logs match up pretty well with what @PureTryOut got on the podman side. I'll attach them here:

[distrobox_logs.txt](https://github.com/89luca89/distrobox/files/8553594/distrobox_logs.txt)
[podman_logs.txt](https://github.com/89luca89/distrobox/files/8553595/podman_logs.txt)


The distrobox logs don't seem to have any useful information from what I can tell, I just did `distrobox create -n test`, followed by `distrobox enter test`.

**Comment by 89luca89** [comment] 2022-04-25 10:35
Ah thanks both guys for the logs ad reports, I might have found the issue, can both of you please give me the output of:

`id -ru; id -rg; id`  ?

I suspect the problem here is that instead of reporting your main group (eg: 1000) `id -rg` is reporting the wheel group (100) 

Thanks!

**Comment by awsomearvinder** [comment] 2022-04-25 10:36
```
1000
100
uid=1000(bender) gid=100(users) groups=100(users),1(wheel)
```

Yep!

**Comment by 89luca89** [comment] 2022-04-25 11:09
Thanks I'll also wait for @PureTryOut feedback on this :+1:

**Comment by 89luca89** [comment] 2022-04-25 16:21
OK it makes sense now
Distrobox uses the primary group id (`id -rg`) to pass for the internal user
Problem here is that primary group Id should be your own one (1000) not others, this indicates some misconfiguration or well I don't know really 😂 

I'll see if I'll find a way to make things a bit more solid for these occasions

**Comment by 89luca89** [comment] 2022-04-25 19:42
And as expected on my alpine the primary group is correctly set, that' why I couldn't reproduce the issue:

```sh
alpine:~$ id
uid=1000(luca-linux) gid=1000(luca-linux) groups=10(wheel),23(input),27(video),105(docker),1000(luca-linux)
alpine:~$ id -ru; id -rg
1000
1000
```

I can reproduce this if I use

`usermod -g wheel`

To add my user to the wheel group, instead of

`usermod -a -G wheel`

As the first command will set that group as the primary group!

I cannot do much about this, as `id` which is the command I use is the standard UNIX and POSIX utility which rightfully reports the primary group.

As this is a misconfiguration on your side, can you try to fix your primary group and retry with a new container?
Obviously keep in mind that that files owned by `1000:10` have to be removed from the host before trying again

**Comment by awsomearvinder** [comment] 2022-04-25 20:27
Sure, I can try that when I get off work. I'll let you know how it goes. It dosen't matter to me but is there any particular reason the primary group id has to match the user id for distrobox to work? I appreciate you looking into all this, and look forward to using this. :)

**Comment by 89luca89** [comment] 2022-04-25 20:38
> Sure, I can try that when I get off work. I'll let you know how it goes. It dosen't matter to me but is there any particular reason the primary group id has to match the user id for distrobox to work? I appreciate you looking into all this, and look forward to using this. :)

Well it does matter for both podman **and** distrobox, as it will map UID and GID of the user to the same UID and GID values inside the container.
If the host can work with a primary group that is not the same as the main user group (because it has access to all the groups) the same is not true inside the container, where you only have your group

So podman will map for example 1000:10 from outside the container to the inside, and distrobox too will work with that IDs, but then you'll just have an user 1000:10 without any other groups, so It will miss the main group

Probably one could work around this by creating all groups-gids which user is part of, inside the container
but that could also lead to incompatibilities and breakage 
(eg wheel already exists and it's 1 instead of 10?)

**Comment by PureTryOut** [comment] 2022-04-26 04:37
Ok so on my laptop, that was the case. However on my desktop, my primary group did seem to be set right.

```
06:36 ~ id
uid=1000(bart) gid=1000(bart) groups=1000(bart),6(disk),10(wheel),20(dialout),23(input),27(video),34(kvm),35(games),100(users),103(plugdev),111(lpadmin),174(qemu),218(libvirt),300(abuild),1002(sambashare)
06:36 ~ id -ru
1000
06:36 ~ id -rg
1000
```

Still, entering the container is broken:

```
06:36 ~ distrobox enter archlinux
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
Starting container archlinux
run this command to follow along:
        podman logs -f archlinux
......
done!
Error: OCI runtime error: crun: open executable: Not a directory

An error occurred

An error occurred
```

(image type doesn't matter)

I'll give changing the primary group a shot on my laptop later though

**Comment by awsomearvinder** [comment] 2022-04-26 07:06
So on my end changing primary group (seems?) to have resolved my issues. I had to run a recursive chown on my home directory too, as well as a reboot. Before the reboot though I noticed some really weird behavior on my system, but that can probably be written off. Some directories in /home/<user>/.local/containers would sometimes be owned by a non-existing user/group on my system (uid/gid 10000) for instance. Just wiping the folder after the reboot and trying again got it all working. 

Even before the reboot though there were some oddities I noticed, such as occasionally my .local's entire directory ownership would change to root, without me even running a command on it. This is a relatively fresh VM I'm working on that's only a few days old which I never had rebooted before, I don't really know what was doing that, but things seem to have stabilized now. 

Rather then my group and user not being the same (bender:bender), I think the underlying cause was whatever was doing that weird behavior, since my entire system was still consistent about it's group ownership, but that's largely speculation admittedly.

**Comment by 89luca89** [comment] 2022-04-26 08:37
> Some directories in /home/<user>/.local/containers would sometimes be owned by a non-existing user/group on my system (uid/gid 10000) for instance. Just wiping the folder after the reboot and trying again got it all working.

@awsomearvinder  That is how user-mapping works on podman, those users that does not exist on your host, are the "root" user inside the podman

> However, still the same error. So I guess this resolves the first issue I mentioned, but Error: OCI runtime error: crun: open executable: Not a directory is still happening.

@PureTryOut can you run the distrobox command with `--verbose`? You can attach it as a file as it will be a big log :+1:

**Comment by PureTryOut** [comment] 2022-04-28 06:10
[distrobox enter archlinux --verbose](https://github.com/89luca89/distrobox/files/8579987/distrobox.log)

**Comment by 89luca89** [comment] 2022-04-28 06:15
> [distrobox enter archlinux --verbose](https://github.com/89luca89/distrobox/files/8579987/distrobox.log)

Can you try creating the container specifying 

`SHELL=/bin/bash distrobox create ...`

You fan set bash zsh or fish, instead of ash now

You probably can also test simply entering 

`distrobox enter your-container -- bash -l`

**Comment by PureTryOut** [comment] 2022-04-28 07:31
> `distrobox enter your-container -- bash -l`

That works.

> `SHELL=/bin/bash distrobox create`

However does not, log is same as before. I rather not have to specify the shell every time :see_no_evil:

**Comment by 89luca89** [comment] 2022-04-28 08:13
Yea problem here is that SHELL is ash, but package providing ash is busybox, so it does not find it.

> However does not, log is same as before. I rather not have to specify the shell every time see_no_evil

You pointed out something really important! `distrobox enter` was not respecting whatever SHELL was set up during creation, I've pushed a commit to fix this behaviour :+1: 
You should be able to just `distrobox enter` now if you specified anothe SHELL during creation

**Comment by PureTryOut** [comment] 2022-04-28 08:20
I guess I'm checking too soon, but it doesn't seem like you pushed something like that?

**Comment by 89luca89** [comment] 2022-04-28 08:30
Yep sorry was still pushing ahaha

**Comment by PureTryOut** [comment] 2022-04-28 09:08
That works indeed, thanks! So the major issue (for this Github issue) left is it failing to realize that Ash is provided by Busybox then. 

Also I'm trying to change the shell used by my user in the container but `chsh` never accepts my password :thinking:

**Comment by 89luca89** [comment] 2022-04-28 09:19
> That works indeed, thanks! So the major issue (for this Github issue) left is it failing to realize that Ash is provided by Busybox then.

Yep I'll open a new feature request for that

> Also I'm trying to change the shell used by my user in the container but `chsh` never accepts my password thinking

Because your user inside the container has the same name and ID, but it's a different systemd without a password, you can either use `sudo` or `su` to change

So for now closing this one, I'll create a new one for ash/busybox detection :+1:

**Closed** 2022-04-28 09:28 UTC
Labels: bug

**Comment by PureTryOut** [comment] 2022-04-28 09:32
Ah yeah that worked. However even though my standard shell is now Fish, entering the container without specifying the shell still opens Bash. :thinking:

**Comment by 89luca89** [comment] 2022-04-28 09:35
Yea because it uses the SHELL variable used during creation, not the chsh one

**Comment by PureTryOut** [comment] 2022-04-28 09:37
Oh derp, so there is no way for it to use Fish by default then, since it's not installed on container creation time and I can thus not set it as default at that time. Too bad, but it's workable. Thanks for your help!

**Comment by 89luca89** [comment] 2022-04-28 09:41
Well the `init` will install fish if it is specified during creation, if it's in the standard repos of the distro that is.
It seems to work as expected on arch ubuntu and fedora

![image](https://user-images.githubusercontent.com/598882/165724877-221ea79a-3be8-4c9c-8f5f-b605b7eade3b.png)

**Comment by PureTryOut** [comment] 2022-04-28 09:43
Works indeed, awesome!
