### ISSUE TITLE
[Error] Can't get Distrobox to run Ubuntu container with systemd by following the documentation

### ISSUE THREAD

**Issue by croosn** [89luca89/distrobox#955] opened 2023-09-05 23:08 UTC
**Describe the bug**
After freshly installing EndeavourOS and Distrobox, I encountered problems while trying to create Ubuntu containers with init systems and Docker support. Both attempts resulted in Docker error messages, stating that the container is not running.

**To Reproduce**
1. Install EndeavourOS.
2. Install Docker.
3. Install Distrobox version 1.5.0.2.
4. Run ```distrobox create -i ubuntu:22.04 --init --additional-packages "systemd libpam-systemd" -n ubuntu1```
5. Run ```distrobox create --root --image ubuntu:22.04 --additional-packages "systemd docker" --init --unshare-ipc --unshare-netns```

**Expected behavior**
I expected the containers to be successfully created and running after executing these commands.

**Logs**
I've attached the --verbose logs as separate files.

**Desktop**
Container Engine: Docker
Docker Version: 24.0.5, build ced0996600
Distrobox Version: 1.5.0.2

**Additional context**
Running in a VirtualBox.

**Comment by croosn** [comment] 2023-09-05 23:09
Here are the logs:
[log1.log](https://github.com/89luca89/distrobox/files/12528996/log1.log)
[log2.log](https://github.com/89luca89/distrobox/files/12528998/log2.log)

**Comment by 89luca89** [comment] 2023-09-06 18:36
Hi @croosn can you post the logs of `docker logs NAME_OF_CONTAINER`? So we can check why this is having an error

**Comment by croosn** [comment] 2023-09-06 20:42
Hi @89luca89 , thanks for addressing this so quickly!

Here is my distrobox list:
```
$ distrobox list
ID           | NAME                 | STATUS             | MEM              | CPU%  | IMAGE                         
206f70c66398 | ubuntu-22-04         | Exited (255) 24 seconds ago | 0B / 0B          | 0.00% | ubuntu:22.04                  
8abdb01b0c67 | ubuntu1              | Exited (255) 6 minutes ago | 0B / 0B          | 0.00% | ubuntu:22.04  
```

And here are the logs:
```
distrobox-enter ubuntu1
docker logs ubuntu1 > ~/Downloads/logs-ubuntu1.log
```
[logs-ubuntu1.log](https://github.com/89luca89/distrobox/files/12542375/logs-ubuntu1.log)

Then
```
distrobox-enter --root ubuntu-22-04
docker logs ubuntu-22-04 > ~/Downloads/logs-ubuntu2.log
```
[logs-ubuntu2.log](https://github.com/89luca89/distrobox/files/12542401/logs-ubuntu2.log)

**Comment by CovenantSquad** [comment] 2023-09-07 08:34
Hi, I'm getting the same issue in EndeavourOS, but not in VirtualBox:

I ran `distrobox-create -i ubuntu -n ubuntu --home /home/user123/Distrobox/ubuntu2 -I` and while the installation seemed to complete successfully, the container did not start:
`Error response from daemon: Container f0c54dfca8c75676826a6b44f709346a22ccd2aa112fc801d95130494aaef885 is not running`.

This is the output from 
`distrobox-enter ubuntu` and `docker logs ubuntu >> ~/ubuntu.log`
`distrobox-enter ubuntu --verbose &> ~/ubuntu_verbose.log`

[ubuntu.log](https://github.com/89luca89/distrobox/files/12546441/ubuntu.log)
[ubuntu_verbose.log](https://github.com/89luca89/distrobox/files/12546558/ubuntu_verbose.log)

**Desktop**
Container Engine: Docker
Docker version 24.0.5, build ced0996600
Distrobox Version: 1.5.0.2

**Comment by 89luca89** [comment] 2023-09-16 14:54
@CovenantSquad you need `--additional-packages` and the systemd packages it's clearly stated in the docs

@croosn 
Sadly the logs are missing the `stderr`, can you please use

`docker logs ubuntu1 > ~/Downloads/logs-ubuntu1.log 2>&1`

`docker logs ubuntu-22-04 > ~/Downloads/logs-ubuntu1.log 2>&1`

So the STDERR is included? Thanks

**Comment by 89luca89** [comment] 2023-09-16 15:04
![image](https://github.com/89luca89/distrobox/assets/598882/79aa1166-5d42-470e-9cf1-37a8a74f8ab1)


As you can see it works for me with the same command you posted
Probably it's a bug already fixed in the latest git version

Please try using the latest version from git, and recreate your boxes

**Comment by 89luca89** [comment] 2023-09-20 16:23
Duplicate of #964 which is resolved

**Closed by 89luca89** 2023-09-20 16:23 UTC
Labels: bug
