### ISSUE TITLE
[Error]: When the container name has dot, distrobox-export is stripping the text after dot

### ISSUE THREAD

**Issue by sonulohani** [89luca89/distrobox#393] opened 2022-09-02 05:06 UTC
**Describe the bug**
My distrobox container name is ubuntu-22.04, however when I export the app for ex: "distrobox-export --app gimp", the desktop file that it creates doesn't have ".04" and has only name till ubuntu-22.

**To Reproduce**

- distrobox create -i docker.io/ubuntu:22.04 --name ubuntu-22.04
- distrobox enter ubuntu-22.04
- sudo apt install gimp
- distrobox-export --app gimp

**Expected behavior**
The desktop file should also have ".04"

**Comment by 89luca89** [comment] 2022-09-02 05:58
Hi @sonulohani 
This has already been solved and It's a duplicate of #375

**Closed by 89luca89** 2022-09-02 05:58 UTC
Labels: bug
