### ISSUE TITLE
[Error] Entering Alpine Linux container fails, "-l: applet not found"

### ISSUE THREAD

**Issue by PureTryOut** [89luca89/distrobox#576] opened 2022-12-31 15:19 UTC
**Describe the bug**
A cleanly created Alpine Linux distrobox can't be entered due to the error mentioned in the title. It can however be entered with regular Podman (`podman exec -it alpine sh`).

I'm guessing `-l` is passed to Busybox (I suppose `busybox -l sh` or something?) but it doesn't know it and thinks it's an applet.

**To Reproduce**

- `distrobox create --image docker.io/library/alpine`
- `distrobox enter alpine`

**Expected behavior**
The shell to "enter" the container and be able to execute commands inside it.

**Logs**
[distrobox-enter-verbose.log](https://github.com/89luca89/distrobox/files/10327549/distrobox-enter-verbose.log)
[podman.log](https://github.com/89luca89/distrobox/files/10327551/podman.log)

**Desktop (please complete the following information):**
Using Podman 4.3.1 and Distrobox 1.4.2.1

**Comment by 89luca89** [comment] 2023-01-16 21:56
Hi @PureTryOut 

I've just tried it, and I cannot reproduce it sadly

![image](https://user-images.githubusercontent.com/598882/212771350-fa8d939f-631d-41fa-a032-c626652c7ebf.png)

**Comment by luigi311** [comment] 2023-01-20 20:59
Trying to run distrobox on my pinephone running pmos edge which is alpine edge and running into the same thing but with ubuntu 22.04 and 20.04

![image](https://user-images.githubusercontent.com/4695527/213804145-2f474393-bbdf-47e7-8550-d79066da0f43.png)

**Comment by 89luca89** [comment] 2023-02-10 09:38
@luigi311 interesting, what is the `$SHELL` variable set to in the host?
Seems like it does not support `-l` flag for login, is it set to `busybox` instead of `sh`?

**Comment by luigi311** [comment] 2023-02-19 22:21
My shell is set to fish. Weirdly enough it seems to be solved now and i am able to create and enter into alpine and fedora now without any issues.

**Comment by 89luca89** [comment] 2023-02-25 09:05
Thanks @luigi311 at this point I'll close this, and if someone else finds this problem, we can reopen :+1:

**Closed by 89luca89** 2023-02-25 09:05 UTC
Labels: bug
