### ISSUE TITLE
[Error] Custom shell not picked up correctly

### ISSUE THREAD

**Issue by renato-dl** [89luca89/distrobox#83] opened 2022-01-01 14:15 UTC
Ciao,
I am on Fedora 35 and use zsh as default shell. When I try to enter a newly created container (using the default image), the following error is shown:

> Error: executable file `zsh` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found

By manually specifying bash as command (`distrobox-enter --name test -- bash -l`), I can successfully enter the container.

According to #2, zsh should be automatically installed when initialising the container, if I understand correctly. Perhaps I'm doing something wrong.

P.S. I find this project very useful. It does everything I wish Toolbx had implemented, such as the possibility to easily export apps and the possibility to specify a different home directory.

Grazie e buon anno.

**Comment by 89luca89** [comment] 2022-01-01 14:27
Ciao @renato-dl :smile: 

Just to check, did you set the SHELL before or after creating the container?

#2 is about installing the default SHELL when creating the container, so if you changed it **after** the container is created, that container will not have zsh installed

if that's the case you can create a new container starting from the one you have using the `--clone` option so you will not lose the setups:

`distrobox-create --clone test --name test-new`

and now it will pick up the new SHELL and install it automatically
Or you can simply install zsh in the container and call it a day

**Comment by renato-dl** [comment] 2022-01-01 14:51
When I created the container, the host default shell was already set to zsh.
If I clone the container and enter the clone, I get the same error.
Perhaps the `distrobox-init` command is not being executed.

If I install zsh manually within the container it enters without issues, but maybe this is only a symptom of a bigger issue.

Thank you.

**Comment by 89luca89** [comment] 2022-01-01 14:53
Yep then there is another problem here, I'll tag this issue as bug and investigate further!

**Comment by 89luca89** [comment] 2022-01-01 14:55
Also do you confirm that on the host $SHELL corresponds to zsh?

**Comment by renato-dl** [comment] 2022-01-01 14:57
If I run `echo $SHELL` in the host the output is: `/usr/bin/zsh`

**Comment by 89luca89** [comment] 2022-01-01 15:02
Steps to reproduce (using ubuntu as test):

```shell
sudo apt install zsh
sudo chsh -s $(which zsh) $USER
reboot
echo $SHELL -> /usr/bin/zsh
distrobox-create
distrobox-enter
```

confirmed there is a problem here.

**Comment by 89luca89** [comment] 2022-01-01 15:14
Fixed in latest commit: 56467d96d324f25e4305a0d4fb8dd3a77e1ad18c
Confirmed now it's working as intended

If something is still wrong feel free to re open the issue or open a new one :+1: 

Thanks for the report!

**Closed by 89luca89** 2022-01-01 15:14 UTC
Labels: bug, help wanted, good first issue, host-distro

**Comment by renato-dl** [comment] 2022-01-01 15:34
Seems to be working fine.
At the very least, now it takes some time to initialize a newly created container 😄, instead of returning immediately.
Excellent job, thank you.

**Comment by renato-dl** [comment] 2022-01-02 12:52
Sorry, I'm here bothering you again.
I've done some more testing creating a new container using `--home`, still having zsh as default host shell.
I have noticed that a new `.zshrc` is created in the container's home and it is used within the container. The first configuration wizard is not shown when entering the container, unless you delete `.zshrc`.

Also, if you want to install Oh My Zsh, it finds the `$ZSH` variable imported from host, which points at the host's Oh My Zsh install. Maybe this variable should not be imported when using a separate home. 

Since they are going to have separate configurations anyway when different home directories are used, perhaps it would make sense not bothering with a custom shell and use the container's default. Don't know, it' just a thought.

**Comment by 89luca89** [comment] 2022-01-02 13:17
> Sorry, I'm here bothering you again. I've done some more testing creating a new container using `--home`, still having zsh as default host shell. I have noticed that a new `.zshrc` is created in the container's home and it is used within the container. The first configuration wizard is not shown when entering the container, unless you delete `.zshrc`.
> 
> Also, if you want to install Oh My Zsh, it finds the `$ZSH` variable imported from host, which points at the host's Oh My Zsh install. Maybe this variable should not be imported when using a separate home.
> 
> Since they are going to have separate configurations anyway when different home directories are used, perhaps it would make sense not bothering with a custom shell and use the container's default. Don't know, it' just a thought.

Yea probably using a custom HOME we should pay a bit of attention to what env variables we let in or not
For now the procedure is let in ALL BUT SOMETHING, probably in the future we will need to switch to an ALLOW SOMETHING approach
