### ISSUE TITLE
sudo distrobox-create / drop permissions / default to --root

### ISSUE THREAD

**Issue by Semnodime** [89luca89/distrobox#588] opened 2023-01-18 02:55 UTC
**Describe the bug**

```
sudo distrobox create --root
Running distrobox-create as sudo is not supported.
 try instead running:
	distrobox-create --root --root
```

**To Reproduce**
```
sudo distrobox create --root
```

**Expected behavior**
Omit `try instead running` message.

Alternatively, **is it possible to let distrobox drop permissions upon being called** via `sudo` and **default to the same behavior as when called** without `sudo` but **with the `--root` flag**?

**Comment by Semnodime** [comment] 2023-01-18 03:07
```
distrobox create --image ubuntu:latest
Image ubuntu:latest not found.
Do you want to pull the image now? [Y/n]: 
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=ubuntu&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
```

Maybe also default to `--root` here?

IMHO `maybe try to run …` messages are bad for UX and are just wasting humanity's time, as the user intend has obviously correctly been identified
and nothing seriously unforgivible would happen when the `--root` behavior would be assumed incorrectly.
(I don't think there's a significant amount of users (if even any) who explicitly want to use `distrobox-create --image` solely for the purpose of testing whether it would fail when not run with the `--root` flag present. If there's doubt, respond to this statement and let's issue a representitive poll on the community then)

**Comment by misobarisic** [comment] 2023-01-18 15:56
There is an open pull request #582 covering this issue

**Comment by 89luca89** [comment] 2023-02-10 09:39
Duplicate of #575

**Closed by 89luca89** 2023-02-10 09:39 UTC
Labels: bug
