### ISSUE TITLE
[Error] Provided config.fish cause error

### ISSUE THREAD

**Issue by SiriosDev** [89luca89/distrobox#1115] opened 2023-12-26 00:34 UTC
**Describe the bug**
I premise that I am Linux newbie so forgive if the terms are not correct

the configuration of fish (`/etc/fish/conf.d/config.fish`) provided by `distrobox`

to be precise fish (latest) doesn't accept the syntax `$(...)`, instead it uses `(...)` without `$`, in fact removing the dollar sign, make fish works correctly again
```fish
/etc/fish/conf.d/config.fish (line 1): $(...) is not supported. In fish, please use '(id)'.
test -z "$USER" && set -Ux USER "$(id -un 2> /dev/null)"
                                 ^
from sourcing file /etc/fish/conf.d/config.fish
	called on line 253 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup
source: Error while reading file '/etc/fish/conf.d/config.fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```
Browsing the repo I found the possible "responsible" code: https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-init#L1749-L1766

**To Reproduce**
 - Having `fish` installed on host
 - Create a container with `distrobox` (in my case Ubuntu 22.04)
 - Enter the container

**Expected behavior**
Fish running normally.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
     - Podman
 - Which version or podman, docker or lilipod?
     - 4.8.2
 - Which version of distrobox?
     - 1.6.0.1
 - Which host distribution?
     - Arch
 - How did you install distrobox?
     - Pacman

**Comment by profetik-777** [comment] 2023-12-26 02:25
@SiriosDev , thanks for submitting. Sometimes noobs just throw their hands up and move on - so appreciate the extra effort.

I'm not sure if non-bash shells are supported. So this technically, might not be a "bug" but an "Out of Scope" use case. 

@89luca89 does "distrobox" as  product care if it is ran through fish command shell? Or it has to be bash? 

My understanding - they diverge enough to discourage bash / fish swap outs - and it isn't assumed that users should expect them to behave the same.

**Comment by SiriosDev** [comment] 2023-12-26 10:23
Don't know if it is out of scope, however being in the distrobox init mentioned above I thought so

**Comment by Yey007** [comment] 2023-12-27 20:09
@SiriosDev upgrading to the lastest fish, 3.6.4, solved the problem for me. For the record though, distrobox seems to be continuously appending the same string of commands to the file on every cold start of the box. I just ended up with this:
```fish
test -z "$USER" && set -Ux USER "$(id -un 2> /dev/null)"
test -z "$UID"  && set -Ux UID "$(id -ur 2> /dev/null)"
test -z "$EUID" && set -Ux EUID "$(id -u  2> /dev/null)"
test -z "$MARONNE" && set -Ux MARONNE "$(id -u  2> /dev/null)"
set -Ux SHELL "$(getent passwd "$USER" | cut -f 7 -d :)"

# This will ensure we have a first-shell password setup for an user if needed.
# We're going to use this later in case of rootful containers
if test -e /var/tmp/.$USER.passwd.initialize
	echo "⚠️  First time user password setup ⚠️ "
	trap "echo; exit" INT
	passwd && rm -f /var/tmp/.$USER.passwd.initialize
	trap - INT
end
test -z "$USER" && set -Ux USER "$(id -un 2> /dev/null)"
test -z "$UID"  && set -Ux UID "$(id -ur 2> /dev/null)"
test -z "$EUID" && set -Ux EUID "$(id -u  2> /dev/null)"
test -z "$MARONNE" && set -Ux MARONNE "$(id -u  2> /dev/null)"
set -Ux SHELL "$(getent passwd "$USER" | cut -f 7 -d :)"

# This will ensure we have a first-shell password setup for an user if needed.
# We're going to use this later in case of rootful containers
if test -e /var/tmp/.$USER.passwd.initialize
	echo "⚠️  First time user password setup ⚠️ "
	trap "echo; exit" INT
	passwd && rm -f /var/tmp/.$USER.passwd.initialize
	trap - INT
end
```
and have ended up with more copies in the past, before I removed the file to clear it. This seems like it could become a serious issue in the long run. 

Additionally, I've been asked for the first time user password setup multiple times in some instances, though I cannot reproduce the issue and it seems to have disappeared.

**Comment by Yey007** [comment] 2023-12-27 20:16
I'm not so good with shell, but I think [this](https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-init#L1751) line might be the issue regarding the duplicates. I've read [here](https://stackoverflow.com/a/59965054) that the double arrow appends instead of overwrites. This appears to be handled correctly in the [bash version](https://github.com/89luca89/distrobox/blob/3435f4d27070a99668bfa29a3e508db4ecc09009/distrobox-init#L1725). But again, I'm not too sure what I'm doing so maybe what I'm saying doesn't make sense.

**Comment by Yey007** [comment] 2023-12-27 21:24
This appears to have fixed all of the issues for me, though I cannot guarantee it. I am willing to pr my (single line) change if necessary.

**Comment by mo-pyy** [comment] 2024-01-09 19:32
I just ran into exactly the same error.

> As far as this issue's actual topic goes, perhaps the dollar signs should be removed to make the script compatible with older versions of fish? I am willing to PR this as well.

I think this would be a good idea, especially for the use case of using stable old distros like ubuntu in which fish won't be upgraded quite some time.

**Closed** 2024-02-03 09:45 UTC
Labels: bug
