### ISSUE TITLE
[Error] fakeroot hangs

### ISSUE THREAD

**Issue by tak2hu** [89luca89/distrobox#678] opened 2023-03-30 00:25 UTC
**Describe the bug**
When running `makepkg` on arch linux container, it hangs on `running fakeroot`. The same with running `makedeb` on an ubuntu focal container, it hangs on `running fakeroot`.

**To Reproduce**
On archlinux container, I typed `yay -S python-fugashi` and hangs at `running fakeroot`. Same on ubuntu with `makedeb` but with a custom simple PKGBUILD I wrote. I even `distrobox create --root`, also hangs.

**Expected behavior**
In a normal docker container with exec -it, `makedeb` runs with no problem

**Logs**
I'll send later

**Desktop:**
- docker
- I'll add details later

**Comment by Curve** [comment] 2023-05-06 12:43
Can confirm this.  
Seems to be new, haven't experienced this in the past

**Comment by 89luca89** [comment] 2023-06-10 08:24
Hi @tak2hu @Curve 
I'm not able to reproduce this on any combination of host/guest I've tried (both rootless and rootful)
fakeroot works instantly for me

At least with podman
Can you try with podman and let me know?

If podman works then we can investigate if that's a docker-only problem, thanks

**Comment by actionless** [comment] 2023-06-27 08:45
add ` --ulimit nofile=1024:524288` to `docker build`

**Comment by 89luca89** [comment] 2023-08-03 16:04
I've tried again both on podman and docker `yay -S python-fugashi` and I didn't occur this

I'll close this as I cannot reproduce

**Closed by 89luca89** 2023-08-03 16:04 UTC
Labels: bug

**Comment by D3vil0p3r** [comment] 2024-03-02 11:52
It can be reproduced by trying to build a tool. Just take a PKGBUILD, as example [ffuf](https://github.com/BlackArch/blackarch/blob/master/packages/ffuf/PKGBUILD), and run `makepkg -f -src --noconfirm`.

**Comment by Ashark** [comment] 2024-04-01 14:01
I can reproduce when using distrobox with `debian:11` image, and trying to build a `fdupes` debian package (following their [tutorial](https://wiki.debian.org/BuildingTutorial)).

I did the following:
```
> docker pull debian:11
> distrobox create --image debian:11 --name debian 11
> distrobox enter debian 11
... # preparation steps to download the package, install dependencies, etc
$ debuild -b -uc -us
... # some info messages
 fakeroot debian/rules clean  # <- hangs at this line
```

Is there any workaround for this?
