### ISSUE TITLE
[Error] Distrobox enter hangs with docker

### ISSUE THREAD

**Issue by jkaleshi14** [89luca89/distrobox#1437] opened 2024-06-12 15:35 UTC
Please, before opening a bug:

- make sure you've read the documentation.
- Ensure there isn't already an open issue about this.
- Ensure there isn't already a closed/resolved issue about this.

**Describe the bug**
When running distrobox enter using docker it just hangs at "Starting container...". 

**To Reproduce**
docker enter

**Expected behavior**
distrobox enter shouldn't hang.

**Logs**
[logs.txt](https://github.com/user-attachments/files/15807480/logs.txt)

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod?
 - docker
 - Which version or podman, docker or lilipod?
 -  26.1.0-ce, build c8af8ebe4a89
 - Which version of distrobox?
 - 1.7.2.1
 - Which host distribution?
 - OpenSuse Tumbleweed
 - How did you install distrobox?
 - zypper install distrobox

**Additional context**
I have ohmyzsh installed

**Comment by 89luca89** [comment] 2024-06-18 15:48
Duplicate of #1382

**Closed by 89luca89** 2024-06-18 15:48 UTC
Labels: bug
