### ISSUE TITLE
[Error] Same error for entering container with --nvidia flag with closed issue

### ISSUE THREAD

**Issue by pathquester** [89luca89/distrobox#1234] opened 2024-02-25 18:14 UTC
**Describe the bug**
I am running into the same issue with: https://github.com/89luca89/distrobox/issues/1095 which was closed and as you commented was supposed to work with latest git version, however it doesn't work for me.

**To Reproduce**
 When trying to enter the container created with --nvidia, it fails with the following errors:
 
```
 + for nvidia_lib in ${NVIDIA_LIBS}
++ printf %s /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
++ sed 's|/run/host/usr/lib/x86_64-linux-gnu/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib/i386-linux-gnu/|/usr/lib/|g'
++ sed 's|/run/host/usr/lib64/|/usr/lib64/|g'
++ sed 's|/run/host/usr/lib32/|/usr/lib/|g'
+ dest_file=/usr/lib64/nvidia/current/libnvidia-ml.so
+ '[' -e /usr/lib64/nvidia/current/libnvidia-ml.so ']'
+ type=file
+ '[' -L /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so ']'
+ type=link
+ '[' link = link ']'
++ dirname /usr/lib64/nvidia/current/libnvidia-ml.so
+ mkdir -p /usr/lib64/nvidia/current
+ cp -d /run/host/usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so /usr/lib64/nvidia/current/libnvidia-ml.so
cp: cannot create symbolic link '/usr/lib64/nvidia/current/libnvidia-ml.so': Read-only file system
+ '[' 1 -ne 0 ']'
Error: An error occurred
+ printf 'Error: An error occurred\n'

```

**Expected behavior**
No errors.

**Logs**
[logs.txt](https://github.com/89luca89/distrobox/files/14397350/logs.txt)

**Desktop (please complete the following information):**
podman
podman version 4.3.1
distrobox version: 1.6.0.1
Debian bookworm
Git

**Additional context**
It was created with distrobox create --nvidia --name arch-nvidia --image docker.io/library/archlinux:latest on Debian bookworm.

**Comment by 89luca89** [comment] 2024-02-26 06:37
@pathquester seeing your log, you're not using the git version of distrobox
The new version will do a checksum match that is missing in your log

**Comment by pathquester** [comment] 2024-02-26 15:33
@89luca89 I am not sure why that is missing since I did git clone and then ./install.

**Comment by pathquester** [comment] 2024-02-26 21:27
@89luca89 I see what happened, the log excerpt that I pasted is indeed from the version I was using before I saw your comment on the original issue to try the latest git version. If you open the [logs.txt](https://github.com/89luca89/distrobox/files/14397350/logs.txt) that I attached though, you will see that I was using the git version during my second test and that the same issue is present.

**Comment by 89luca89** [comment] 2024-02-26 21:35
Aaah got it! Thanks!

Can you do an `ls -laH /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so` on the host?

It seems like, we correctly mount /usr/lib/x86_64-linux-gnu/nvidia/ into /usr/lib64/nvidia, in readonly mode
But that file seems to be non-existent on the guest side

Maybe it's a broken link? Can you show that?

**Comment by pathquester** [comment] 2024-02-26 21:36
`-rw-r--r-- 1 root root 1827448 Oct 25 23:21 /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-ml.so
`

**Comment by 89luca89** [comment] 2024-02-26 21:54
so it's a proper file, not a symlink

it's strange because in the log, at line `54957`, it correctly mounts `/run/host/usr/lib/x86_64-linux-gnu/nvidia` onto  `/usr/lib64/nvidia`, this should include `current` and subsequent files

Line `69391` returns that the file is a symlink actually

**Comment by 89luca89** [comment] 2024-02-26 22:19
![image](https://github.com/89luca89/distrobox/assets/598882/633326a9-dd25-4673-aec0-c83dc87e3930)

On a fresh debian bookworm VM with `nvidia-drivers` installed via apt, this works correclty

**Comment by pathquester** [comment] 2024-02-26 22:33
@89luca89 Ah, strange. I am not sure where is the difference.

**Comment by pathquester** [comment] 2024-02-27 08:56
@89luca89 The strange thing is that a debian image works flawlessly, the issue is only with arch.

**Comment by 89luca89** [comment] 2024-02-28 18:44
Probably because with debian-to-debian it doesn't need to translate paths, and if there are absolute links or stuff like this, it works correctly ootb

Anyway I couldn't reproduce this on debian bookworm, testing and unstable, and also on ubuntu, so I think there must be something else specific to your setup/system :man_shrugging:

**Comment by 89luca89** [comment] 2024-05-01 10:22
Closing as this seems non-reproducible

**Closed** 2024-05-01 10:22 UTC
Labels: bug
