### ISSUE TITLE
[Error] Can't use distrobox-enter on nixos using podman

### ISSUE THREAD

**Issue by axtloss** [89luca89/distrobox#158] opened 2022-02-01 13:52 UTC
**Describe the bug**
I can't enter any distrobox I made using distrobox-create, `distrobox-enter --name <name>` always fails

**To Reproduce**
create a distrobox container with
`distrobox create --image <image> --name <name>` (I've tested both fedora 35 from registry.fedora as well as arch)
`distrobox-enter --name <name>`

**Expected behavior**
The distrobox container properly launches and I get put into a shell in that container.

**Logs**
[distrobox-log.txt](https://github.com/89luca89/distrobox/files/7978908/distrobox-log.txt)
[podman-log.txt](https://github.com/89luca89/distrobox/files/7978909/podman-log.txt)

**Desktop (please complete the following information):**
 - OS: nixos
 - Version 22.05 (unstable)

**Additional context**
Not sure if that's relevant, but when I run distrobox-enter with sudo it erros with `Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver`

**Comment by 89luca89** [comment] 2022-02-01 14:05
Hi @axtloss 

Can you please past here the output of
`podman info`
and of all the files in `~/.config/containers/` ? 

thanks!

**Comment by axtloss** [comment] 2022-02-01 14:14
this i the podman info:
[podman-info.txt](https://github.com/89luca89/distrobox/files/7979044/podman-info.txt)

`~/.config/containers` doesn't exist, the closest I've found is `~/local/share/containers/`

**Comment by 89luca89** [comment] 2022-02-01 14:23
Are you able to run normal podman containers in rootless mode?

As a normal user can you run:

`podman run --rm -ti alpine:latest sh`

it that works, try also this command:

`podman run --rm -ti --hostname test-pod --ipc host --name fedora-toolbox-35 --network host --privileged --security-opt abel=disable --user root:root --pid host --userns keep-id --ulimit host alpine:latest sh`

Thanks for the collaboration :smile: :

**Comment by 89luca89** [comment] 2022-02-01 14:29
Can you post me the logs of running the same command above but with 

`--log-level debug` put between `podman` and `run`

I suspect there is a podman problem here

**Comment by axtloss** [comment] 2022-02-01 14:33
[podman-run-log.txt](https://github.com/89luca89/distrobox/files/7979204/podman-run-log.txt)
I've tried using docker with distrobox too, but that didn't work either (I had it configured to work without root)

**Comment by 89luca89** [comment] 2022-02-01 14:40
I'm downloading an iso of nixos unstable, I'll try it out, I'm no nixos expert but I suspect there is something around podman not working

**Comment by 89luca89** [comment] 2022-02-01 14:52
> I've installed podman with
> 
> ```nix
> virtualisation.podman = {
>      enable = true;
> 
>       dockerCompat = true;
>     };
> ```
> 
> It'll probably be easier to reproduce the issue that way

I think you also need to follow this to set up rootless podman: https://gist.github.com/adisbladis/187204cb772800489ee3dac4acdd9947

**Comment by axtloss** [comment] 2022-02-01 14:57
Nope, that still returns the same error.

**Comment by 89luca89** [comment] 2022-02-01 15:06
That's strange
I've set up a Nixos VM using this iso: https://releases.nixos.org/nixos/unstable/nixos-22.05pre350017.efeefb2af14/nixos-gnome-22.05pre350017.efeefb2af14-x86_64-linux.iso

Added: 
```nix
virtualisation.podman = {
     enable = true;

      dockerCompat = true;
    };
```

to /etc/nixos/configuration.nix

Launched a `nixos-rebuild switch`

and it worked right away with podman, both `distrobox` and 

```
podman run --rm -ti --hostname test-pod --ipc host --name fedora-toolbox-35 --network host --privileged --user root:root --pid host --userns keep-id --ulimit host alpine:latest sh
```

These are my podman info for reference:

[podman-info.2.txt](https://github.com/89luca89/distrobox/files/7979421/podman-info.2.txt)

Seems more to me a problem with `podman` and `zfs` storage backend

**Comment by 89luca89** [comment] 2022-02-01 15:11
> when comparing the output, I found that the configFile points to `/home/amy/.config/containers/storage.conf`, which doesn't exist for me. Could that be the issue?

I notices that, but even for me it does not exist

**Comment by 89luca89** [comment] 2022-02-01 15:12
https://www.jwillikers.com/podman-with-btrfs-and-zfs

Probably need to use the zfs driver

**Comment by axtloss** [comment] 2022-02-01 15:16
After doing what it said I'm not even able to create a container with distrobox-create anymore, it just errors with `ERRO[0000] User-selected graph driver "zfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve
Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
`

**Comment by 89luca89** [comment] 2022-02-01 15:22
Probably you need to delete the ~/.local/share/containers and start from scratch I suppose
But I don't really know about this, I suggest you to open a bug on `podman` repo, asking why 

`podman run --rm -ti --hostname test-pod --ipc host --name fedora-toolbox-35 --network host --privileged --user root:root --pid host --userns keep-id --ulimit host alpine:latest sh`

doesn't work, describing your setup with ZFS and rootless podman

---

About docker instead? are you able to run this?

`docker run --rm -ti --hostname test-pod --ipc host --name fedora-toolbox-35 --network host --privileged --user root:root --pid host --userns keep-id --ulimit host alpine:latest sh`

**Comment by axtloss** [comment] 2022-02-01 15:33
Running that command just returns `invalid argument "host" for "--ulimit" flag: invalid ulimit argument: host`, however, I tried running distrobox again and now distrobox-enter got a bit further, I saw pacman/pacstrap output but it failed with `2022-02-01T15:32:21.637148000Z Warning: there was a problem setting up the user
2022-02-01T15:32:21.642850000Z Error: An error occurred`

**Comment by 89luca89** [comment] 2022-02-01 15:41
Sorry I pasted the wrong command for docker, it is this one:

`docker run --rm -ti --hostname test-pod --ipc host --name fedora-toolbox-35 --network host --privileged --user root:root --pid host alpine:latest sh`

About that warning error, it seems podman went ahead and it worked, so now the problem is in the `init`

We can start from scratch and post me the logs of this:

```
distrobox create --image archlinux:latest --name bugreport-arch
distrobox enter --name  bugreport-arch
```

After we have the error just run

`podman logs  bugreport-arch`

So we can check what's wrong

Thanks!

**Comment by axtloss** [comment] 2022-02-01 15:45
The first docker command works fine, since I switched to docker I ran `docker logs bugreport-arch` instead, it seems like the prompt for setting the password doesn't work
[docker-arch-bugreport.txt](https://github.com/89luca89/distrobox/files/7979759/docker-arch-bugreport.txt)

**Comment by 89luca89** [comment] 2022-02-01 15:52
cool so now we have another problem :smile: 

you need to use version 1.2.13 of distrobox (directly from git) because `useradd` fails for the presence of 
the `nscd` fixed in this commit https://github.com/89luca89/distrobox/commit/6186c105654f07179fbf5e942c32cac99b2b3c62

Please try with the version from git it should work

**Comment by axtloss** [comment] 2022-02-01 16:07
It works now! I'm able to create and enter the distrobox container. Thanks for the quick help!

**Comment by 89luca89** [comment] 2022-02-01 16:14
Thanks to you for the reporting!

Closing then, feel free to open a new one if you have other problems :smile:

**Closed by 89luca89** 2022-02-01 16:14 UTC
Labels: bug
