### ISSUE TITLE
[Suggestion] Request(I mean, humble request) for support for Android or any Android based distro as guest os

### ISSUE THREAD

**Issue by rairay91** [89luca89/distrobox#1535] opened 2024-08-28 12:00 UTC
I know there is waydroid which just works but not as expected. And waydroid don't like btrfs snapshots system. Once you rollback to any snapshot waydroid is dead, even if we rollback to original state waydroid will still not work. So only choice we left with is reinstalling and setting up everything again and again.
Also waydroid has lot of problems that I can't explain.

Distrobox on the other hand i use for everything. For example My host distro is Garuda Kde Draganized, and i have setup ubuntu within distrobox where i set up ComfyUI with blender and krita, another arch based dostro where every other package from aur which me eventually break system.

If i use distrobox for everything then why not for android.
I know something might be difficult but not impossible.
If android itself is not possible to install then may android based distro for pc which allow us to install android app with playstore. Something like Bliss os, Chrome os, Prime os, Fyde os, Phoenix os or maybe any other android distro. And also including translation layers like Libhiudini(for intel) and Libndk(for amd).

**Comment by 89luca89** [comment] 2024-10-12 11:39
Duplicate of https://github.com/89luca89/distrobox/issues/725

**Closed by 89luca89** 2024-10-12 11:39 UTC
Labels: enhancement
