### ISSUE TITLE
[Error] distrobox-create: Creating 'distrobox' using image [..] Error: host directory cannot be empty

### ISSUE THREAD

**Issue by juhp** [89luca89/distrobox#440] opened 2022-09-26 12:53 UTC
**Describe the bug**
distrobox-create from current git run from outside the tree failed for me.

**To Reproduce**
`distrobox-create -n fedora-37-distrobox -i fedora:37`

**Expected behavior**
No error

**Logs**
[db.log](https://github.com/89luca89/distrobox/files/9646314/db.log)

**Desktop (please complete the following information):**
 - Are you using podman or docker?  podman-4.2.0-2.fc36
 - Which version of distrobox? git and 1.4.1

**Additional context**
1.4.1 works okay

**Comment by 89luca89** [comment] 2022-09-26 14:48
Can you check where you have `distrobox-host-exec`?

Seems like it's in some way not found?

`		--volume "":/usr/bin/distrobox-host-exec:ro`

**Comment by 89luca89** [comment] 2022-10-19 17:54
Any news @juhp ?

**Comment by 89luca89** [comment] 2022-10-26 08:35
@juhp 
I think if you use aliases instead of symlinks it should act normally, even using whatever path you want to install distrobox
At this point I'd mark this as a duplicate of #315  as it's stemming from the same problem :+1:

**Closed by 89luca89** 2022-10-26 08:35 UTC
Labels: bug
