### ISSUE TITLE
[Error] Mounting issues making fedora dbxes unusable

### ISSUE THREAD

**Issue by misobarisic** [89luca89/distrobox#263] opened 2022-05-09 13:06 UTC
**Describe the bug**
After creating and entering a `fedora:latest` or `fedora:rawhide` box, dependency installation completes but mounting creates an issue.

**To Reproduce**
Use a host system with no `/run/host`.

**Expected behavior**
A working distrobox.

**Logs**
These are the last few lines when entering:
```
Complete!
/etc/host.conf is not a mountpoint
/etc/localtime is not a mountpoint
Warning: failed to bind mount /run/host/etc/localtime to /etc/localtime
Error: An error occurred

An error occurred
```

I am using the latest commit version of distrobox and podman 4.1.0.

**Comment by 89luca89** [comment] 2022-05-09 13:50
well It's strange, I mean `/run/host` is something created by distrobox, where the root filesystem of the host is mounted
No host disto has `/run/host` by default :thinking: 

Is it working now? Can you create other distroboxes to check if error occurs?

**Comment by misobarisic** [comment] 2022-05-09 14:42
> well It's strange, I mean `/run/host` is something created by distrobox, where the root filesystem of the host is mounted No host disto has `/run/host` by default thinking
> 
> Is it working now? Can you create other distroboxes to check if error occurs?

The issue at hand only happens with fedora, other images work fine.

**Comment by misobarisic** [comment] 2022-05-09 14:54
> if you create new fedora distroboxes? have the error?

Yes.

**Comment by 89luca89** [comment] 2022-05-09 14:55
Ok, can you send the logs of the errors? Thanks

**Comment by 89luca89** [comment] 2022-05-09 15:30
Seems to be a problem with localtime, will check that out thanks! :+1:

**Comment by 89luca89** [comment] 2022-05-09 16:20
I'm testing on an Arch box I have and a Manjaro one, and I can't seem to reproduce the bug 
I'll wait for someone else also to present this to investigate further

In the meantime, can you give me the output of

`ls -la /etc/localtime`

thanks

**Comment by misobarisic** [comment] 2022-05-09 17:10
> In the meantime, can you give me the output of
> 
> `ls -la /etc/localtime`

This is the output: `lrwxrwxrwx 1 root root 33 ruj  22  2021 /etc/localtime -> /usr/share/zoneinfo/Europe/Zagreb`

**Comment by 89luca89** [comment] 2022-05-09 21:39
@misobarisic can you test this branch? I've pushed a fix that might just work for that issue:

https://github.com/89luca89/distrobox/tree/fix/263

**Comment by misobarisic** [comment] 2022-05-10 05:11
> @misobarisic can you test this branch? I've pushed a fix that might just work for that issue:
> 
> https://github.com/89luca89/distrobox/tree/fix/263

Works fine now. Thanks

**Comment by 89luca89** [comment] 2022-05-10 07:03
Merged and Fixed :+1:

**Closed** 2022-05-10 07:02 UTC
Labels: bug
