### ISSUE TITLE
[Error] microphone, speakers, and webcam are not found

### ISSUE THREAD

**Issue by LukeShortCloud** [89luca89/distrobox#1197] opened 2024-02-09 16:07 UTC
**Describe the bug**
In a container, using applications such as Cheese or Firefox for web conferencing do not work. They do not show my microphone or webcam devices (both are plugged in via separate USB ports).

**To Reproduce**
- Plug a USB device in for a microphone and/or webcam.
- Create a container with systemd support: `distrobox create --init --additional-packages "systemd" --image fedora:38 fedora38`
- Install a desktop environment: `sudo dnf groupnstall "KDE Plasma Workspaces"`
    - You may be able to skip this step by just running `sudo dnf install cheese`
- On the host, launch the desktop environment.
```
mkdir ~/.local/bin/
echo '#!/bin/bash
xhost +SI:localuser:$USER
/usr/bin/distrobox-enter --no-tty --name fedora38 -- "/usr/bin/startplasma-x11"' | tee /var/home/user/.local/bin/plasma-x11-distrobox
chmod +x /var/home/user/.local/bin/plasma-x11-distrobox
xinit /var/home/user/.local/bin/plasma-x11-distrobox -- :4
```
- Launch Cheese or Firefox. With Firefox, go to `meet.google.com` to start a new instant meeting.
    - In the settings of Google Meet, it shows that no devices have been detected. There was no prompt to allow devices. Cheese (a local webcam utility) also shows no audio or video input.

**Expected behavior**
Cheese, Firefox, and other applications can find and use the plugged in microphone(s) and webcam(s).

**Logs**
I checked `podman logs fedora38` and did not see anything relevant. Let me know if there are any specific log files needed.

**Desktop (please complete the following information):**
 - Are you using podman, docker or lilipod? podman
 - Which version or podman, docker or lilipod? 4.8.3
 - Which version of distrobox? 1.6.0.1
 - Which host distribution? Fedora Silverblue 38
 - How did you install distrobox? `sudo rpm-ostree install distrobox`

**Additional context**
SELinux is in permissive mode (not enforcing) to avoid false-positive issues with distrobox.

**Comment by LukeShortCloud** [comment] 2024-02-09 16:21
I also noticed that my audio output to my speakers does not work (no devices are found in the container). They are plugged into a 3.5mm audio output jack on the back of my desktop.

**Comment by LukeShortCloud** [comment] 2024-02-16 18:52
I re-tested with Fedora 39 (Fedora Silverblue 39 and a Fedora 39 container) and the results are the same.

Are you using podman, docker or lilipod? podman
Which version or podman, docker or lilipod? 4.9.0
Which version of distrobox? 1.6.0.1
Which host distribution? Fedora Silverblue 39
How did you install distrobox? `sudo rpm-ostree install distrobox`

I also tried the `export PIPEWIRE_RUNTIME_DIR=/dev/null` workaround to use PulseAudio instead of PipeWire and that did not work.

https://github.com/89luca89/distrobox/blob/main/docs/posts/steamdeck_guide.md

**Comment by 89luca89** [comment] 2024-02-17 08:22
@LukeShortCloud does it work if you use distrobox normally in your environment?

What I mean is, you mention that you use distrobox to launch a full KDE session, which is **an highly experimental setup** (as clearly written in the blog post) 

Can you try in you main session, to launch a distrobox with `distrobox create --init --additional-packages "systemd" --image fedora:38 fedora38` and from there launch firefox and meet and check if that works?

I personally cannot reproduce with this "not a full session" setup

**Comment by LukeShortCloud** [comment] 2024-02-19 18:30
Hey @89luca89 , thanks for getting back to me. I completely understand that running a desktop environment is highly experimental.

I did a minimal test, without the desktop environment, and all of my audio and webcam devices appeared in Google Meet at first.

```
distrobox create --init --additional-packages "systemd" --image fedora:38 fedora38
distrobox enter fedora38 -- sudo dnf -y install firefox
distrobox enter fedora38 -- firefox
```

However, I have found that running web browsers (Chromium and Firefox) are very unstable when ran through Distrobox. They constantly keep crashing. I know that is a separate issue and potentially outside the scope of Distrobox. Here's an example log from Firefox:

```
[Parent 4754, IPC I/O Parent] WARNING: process 5127 exited on signal 11: file /builddir/build/BUILD/firefox-122.0.1/ipc/chromium/src/base/process_util_posix.cc:265
[Parent 4754, IPC I/O Parent] WARNING: process 5170 exited on signal 11: file /builddir/build/BUILD/firefox-122.0.1/ipc/chromium/src/base/process_util_posix.cc:265
[Parent 4754, IPC I/O Parent] WARNING: process 5167 exited on signal 11: file /builddir/build/BUILD/firefox-122.0.1/ipc/chromium/src/base/process_util_posix.cc:265
[GFX1-]: wr_window_new: Thread(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })
[GFX1-]: Failed to connect WebRenderBridgeChild. isParent=true
[GFX1-]: Fallback WR to SW-WR
```

Eventually, my audio input and output devices stop showing up. I assume something to do with the web browser crashing having an affect. Restarting the container does not help.

**Comment by 89luca89** [comment] 2024-02-19 19:12
Hey @LukeShortCloud is this with the last version from git?

**Comment by LukeShortCloud** [comment] 2024-02-20 23:01
No, I have been doing all my tests on the stable release of Distrobox 1.6.0.1 (installed via the official RPM from Fedora).

**Comment by 89luca89** [comment] 2024-02-21 08:35
Can you please test with latest git version, there are many fixes for initful systems and this issue might be already solved, as I cannot reproduce it

**Comment by LukeShortCloud** [comment] 2024-03-02 04:56
I re-tested with Distrobox 1.7.0 using a Fedora 39 host and container. It's working now when launching individual applications!

When launching a full desktop environment, it is still missing audio and webcam support. I understand that it is still experimental to use Distrobox that way.

**Comment by 89luca89** [comment] 2024-05-01 10:21
> When launching a full desktop environment, it is still missing audio and webcam support. I understand that it is still experimental to use Distrobox that way.

This is out of scope of the tool as stated in the experiment article :)

So I'll mark this as fixed now

**Closed by 89luca89** 2024-05-01 10:21 UTC
Labels: bug, wait-on-user
