### ISSUE TITLE
[Error] Distrobox won't work on opensuse

### ISSUE THREAD

**Issue by razouck** [89luca89/distrobox#563] opened 2022-12-18 14:57 UTC
**Describe the bug**
Archlinux container won't work properly after installing it on OpenSUSE. After it is installed, it can't run pacman. It says `sudo: pacman: command not found`.

**To Reproduce**
First install podman -- distrobox won't even create a container with docker, by the way --, then run `distrobox create archlinux`.

**Expected behavior**
Pacman is supposed to have been found on a arch.

**Logs**
Run the commands with `--verbose` and post the log here as a file upload
Attach also the output of `podman logs` or `docker logs`, possibly with `--latest` flag

_Can't do that_.

**Desktop (please complete the following information):**
 - Are you using podman or docker? **Podman**.
 - Which version or podman or docker? *4.3.1*.
 - Which version of distrobox? **1.4.1**

**Comment by profetik-777** [comment] 2022-12-19 04:05
+1 I think I am also seeing this in MicroOSD.

**Comment by dfaggioli** [comment] 2022-12-19 05:49
> **Describe the bug** Archlinux container won't work properly after installing it on OpenSUSE. After it is installed, it can't run pacman. It says `sudo: pacman: command not found`.
> 
> **To Reproduce** First install podman -- distrobox won't even create a container with docker, by the way --, then run `distrobox create archlinux`.
> 
Well, you are not creating an Arch Linux container, with this command, so there's no wonder there's no `pacman`. Check (and post) the content of `/etc/oa-release`.

Basically, you need to tell `distrobox-create` which image you want to use (which in you're case is an Arch one). If you don't do that, it'll just use the default, which on openSUSE is a Tumbleweed one.

Have a look at the docs for distrobox-create.

This should IMO be closed as not-a-bug.

> **Expected behavior** Pacman is supposed to have been found on a arch.
> 
Yeah, if you create an Arch container, I'm sure it will. :-)

**Comment by 89luca89** [comment] 2022-12-19 12:10
Indeed it's not a bug
If you don't specify an image, distrobox will fallback to its defaults

**Closed by 89luca89** 2022-12-19 12:10 UTC
Labels: bug

**Comment by razouck** [comment] 2022-12-22 21:12
> Have a look at the docs for distrobox-create.
> 
> This should IMO be closed as not-a-bug.

Where are them? `man distrobox` doesn't mention where I can find the link of the correct image. Also, the same command works on Fedora.

**Comment by juhp** [comment] 2022-12-23 05:51
`distrobox-create --help`

It is `distrobox-create `*`--image`*` archlinux` not `distrobox-create archlinux`

I make this mistake often enough myself that I overrode the default image to be a non-existent one...

**Comment by razouck** [comment] 2022-12-25 20:24
> It is `distrobox-create `_`--image`_` archlinux` not `distrobox-create archlinux`

Oh, yeah, so that must be why it worked on Fedora, because back then I actually read the `--help` page. Thank you.
