### ISSUE TITLE
Save / Load of image and final distrobox-create increases the image size by factor 2 ?!

### ISSUE THREAD

**Issue by kkarsten62** [89luca89/distrobox#87] opened 2022-01-01 18:55 UTC
Hi Luca,

I have ported my Python/Qt/ANT app to some more machines. All is working well - great :-). But I notice that the size of the initial image will be increase by nearly a factor of 2 on the final  distrobox-create.

Simple question: is this behaviour a normal one?

Maybe you could check on your side.

Karl ...

Here the commands to reproduce, done with latest curl version 1.2.7 on Fedora 33 with podman version 3.3.1:

	distrobox-create --name test --image ubuntu:20.04
	distrobox-enter --name test
	sudo apt install gedit (install something which fills the container)
	CTRL-D

	podman image ls -a
	REPOSITORY                      TAG         IMAGE ID      CREATED       SIZE
	docker.io/library/ubuntu        20.04       ba6acccedd29  2 months ago  151 MB

	podman container commit -p test test_export
	
	podman image ls -a
	REPOSITORY                      TAG         IMAGE ID      CREATED        SIZE
	localhost/test_export           latest      684b7c16b6ba  2 minutes ago  1.06 GB
	docker.io/library/ubuntu        20.04       ba6acccedd29  2 months ago   151 MB

	podman save localhost/test_export:latest | gzip > test_export.tar.gz

Copy archive file to a next machine:

	podman load < test_export.tar.gz
	
	podman image ls -a
	REPOSITORY                      TAG         IMAGE ID      CREATED         SIZE
	localhost/test_export           latest      684b7c16b6ba  11 minutes ago  1.06 GB

	distrobox-create --image localhost/test_export:latest --name test_export

	podman image ls -a
	REPOSITORY                      TAG         IMAGE ID      CREATED         SIZE
	localhost/test_export           latest      684b7c16b6ba  14 minutes ago  2.32 GB

Now the image size increase from 1.06 GB to 2.32 GB!

**Comment by 89luca89** [comment] 2022-01-01 20:38
Hi @kkarsten62 
I've just did the process you described but it remained the same for me
both on Ubuntu 20.04 and Fedora 35 hosts, both with docker and podman

Not sure if it's something to do with podman in your case. It's not that distrobox does something super-fancy with podman commands anyway :smile: 

Will leave open in case someone else can reproduce this

**Comment by alcir** [comment] 2022-01-01 21:26
I am not able to reproduce it either.
However it is pretty strange that the image changes its size by creating a container.

**Comment by 89luca89** [comment] 2022-01-01 21:29
Yea it's pretty strange and I see that the image ID remains the same
This leads me to think that it can probably be a problem with podman reporting on an older version?

**Comment by kkarsten62** [comment] 2022-01-01 21:53
Really strange. I can reproduce in a VM with Fedora 35 with default installed Podman.
I cleaned first all containers and images with rm -f.
Then I create the container with the gedit package. (set keyboard and language to German during installation)
Then I commit and save to the *.tar.gz
Then I delete again the containers and images.
Then I load the image back and run the distrobox-create.
==> Size increased from 1.06 GB to 2.32 GB on the final distrobox-create.
I will check tomorrow in a fresh new VM Fedora 35.

**Comment by 89luca89** [comment] 2022-01-01 22:22
@kkarsten62 just tried now on a fresh F35 VM

```shell
[luca-linux@fedora ~]$ podman stop fedora-toolbox-35 
fedora-toolbox-35

[luca-linux@fedora ~]$ podman container commit fedora-toolbox-35 test_export
Getting image source signatures
Copying blob 334865ef4c9b skipped: already exists  
Copying blob f99b9f453527 skipped: already exists  
Copying blob c1e0dde12acc done  
Copying config bd4e2e37d6 done  
Writing manifest to image destination
Storing signatures
bd4e2e37d61ef04f5afc187f384272d72890a5ad7b9d66aa220f56e14d13218f

[luca-linux@fedora ~]$ podman images
REPOSITORY                                 TAG     IMAGE ID      CREATED             SIZE
localhost/test_export                      latest  bd4e2e37d61e  About a minute ago  856 MB
registry.fedoraproject.org/fedora-toolbox  35      ab8bc106d4a7  2 months ago        332 MB

[luca-linux@fedora ~]$ podman save localhost/test_export:latest | gzip > test_export.tar.gz
Copying blob 334865ef4c9b done  
Copying blob f99b9f453527 done  
Copying blob c1e0dde12acc done  
Copying config bd4e2e37d6 done  
Writing manifest to image destination
Storing signatures

[luca-linux@fedora ~]$ ls -lah test_export.tar.gz 
-rw-rw-r--. 1 luca-linux luca-linux 391M Jan  1 23:18 test_export.tar.gz

[luca-linux@fedora ~]$ podman load < test_export.tar.gz
Getting image source signatures
Copying blob c1e0dde12acc done
Copying blob f99b9f453527 skipped: already exists
Copying blob 334865ef4c9b skipped: already exists
Copying config bd4e2e37d6 done
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/test_export:latest

[luca-linux@fedora ~]$ podman images
REPOSITORY                                 TAG     IMAGE ID      CREATED        SIZE
localhost/test_export                      latest  bd4e2e37d61e  5 minutes ago  856 MB
registry.fedoraproject.org/fedora-toolbox  35      ab8bc106d4a7  2 months ago   332 MB

[luca-linux@fedora ~]$ distrobox create --image localhost/test_export:latest --name test_imported_back
59a73973a6f5718e341213559c422b35b283a316fdae31c7515e59712eb423f9
Distrobox 'test_imported_back' successfully created.
To enter, run:
	distrobox-enter --name test_imported_back

[luca-linux@fedora ~]$ distrobox enter --name test_imported_back
Starting container test_imported_back
run this command to follow along:
	podman --remote logs -f test_imported_back
.
done!
[luca-linux@test_imported_back ~]$ exit
logout

[luca-linux@fedora ~]$ podman images
REPOSITORY                                 TAG     IMAGE ID      CREATED        SIZE
localhost/test_export                      latest  bd4e2e37d61e  5 minutes ago  856 MB
registry.fedoraproject.org/fedora-toolbox  35      ab8bc106d4a7  2 months ago   332 MB


```

**Comment by kkarsten62** [comment] 2022-01-01 22:32
Thanks Luca.

In parallel I checked in a Ubuntu 18.04 VM.
Here the size remains the same - good :-)

I will check also in fresh F35 VM tomorrow.

**Comment by kkarsten62** [comment] 2022-01-02 11:15
Hi,
sorry - but I can not confirm for Fedora 35.
[F35_log.pdf](https://github.com/89luca89/distrobox/files/7798961/F35_log.pdf)

I set up a fresh new VM by using [Cockpit](https://cockpit-project.org/) and update all packages.
Then I run exactly the same commands from above. Please see attached log as PDF.
May be you can follow exactly the same commands. On final `distrobox-create` the size increase by factor ~2.

**Comment by 89luca89** [comment] 2022-01-02 11:18
I'll try again with an ubuntu container like you
Just to troubleshoot and rule out that distrobox is doing something wrong
can you do the same, but instead of the last `distrobox-create` you do `podman run -ti image-name:version sh`

**Comment by 89luca89** [comment] 2022-01-02 11:22
Also just to check if it's a visual/reporting problem and not really doubling the size on disk, you can see if a

`df -hT /home`

reports different values before and after the last `distrobox-create`

**Comment by kkarsten62** [comment] 2022-01-02 11:38
Here are my log when using `podman run -ti image-name:version sh` ==> Size remains on 1.06 GB!
```
[karl@fedora ~]$ podman container ls -a
CONTAINER ID  IMAGE                         COMMAND               CREATED         STATUS             PORTS       NAMES
5268b3b5a12e  localhost/test_export:latest  /usr/bin/entrypoi...  41 minutes ago  Up 41 minutes ago              test_export

[karl@fedora ~]$ podman container rm -f 5268b3b5a12e
5268b3b5a12ec95853fe993eabcf633a9458cc6aabfee6b6b163f62c775adab8

[karl@fedora ~]$ podman image ls -a
REPOSITORY             TAG         IMAGE ID      CREATED         SIZE
localhost/test_export  latest      aec3c4c4804b  50 minutes ago  2.32 GB

[karl@fedora ~]$ podman image rm -f aec3c4c4804b
Untagged: localhost/test_export:latest
Deleted: aec3c4c4804b2748b7ddd61d7a65926019a30cf2e6d6ef0a1f0aba0310187690

[karl@fedora ~]$ podman load < test_export.tar.gz
Getting image source signatures
Copying blob e100e106c3da skipped: already exists  
Copying blob 4c398f2d4043 done  
Copying config aec3c4c480 done  
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/test_export:latest

[karl@fedora ~]$ podman image ls -a
REPOSITORY             TAG         IMAGE ID      CREATED         SIZE
localhost/test_export  latest      aec3c4c4804b  52 minutes ago  1.06 GB

[karl@fedora ~]$ podman run -ti localhost/test_export:latest sh
# pwd   
/
# ls
bin  boot  dev	etc  home  lib	lib32  lib64  libx32  media  mnt  opt  proc  root  run	sbin  srv  sys	tmp  usr  var
# gedit
Unable to init server: Could not connect: Connection refused

(gedit:3): Gtk-WARNING **: 11:29:25.112: cannot open display: 
# exit

[karl@fedora ~]$ podman run -ti localhost/test_export:latest sh
# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
# exit

[karl@fedora ~]$ podman image ls -a
REPOSITORY             TAG         IMAGE ID      CREATED         SIZE
localhost/test_export  latest      aec3c4c4804b  54 minutes ago  1.06 GB
[karl@fedora ~]$ 
```

**Comment by 89luca89** [comment] 2022-01-02 11:41
Done same test using your previous log and doing the same commands and I cannot reproduce...

[fedora-podman.log](https://github.com/89luca89/distrobox/files/7798984/fedora-podman.log)

This is increasingly strange

> Here are my log when using podman run -ti image-name:version sh ==> Size remains on 1.06 GB!

I see and can you do a `df -hT $HOME` before and after the last `distrobox-create` which increases the size?

**Comment by kkarsten62** [comment] 2022-01-02 11:54
Here are the log for `df -hT $HOME`. Size increase on file system.

```
[karl@fedora ~]$ podman container ls -a
CONTAINER ID  IMAGE                         COMMAND     CREATED         STATUS                     PORTS       NAMES
408e5bbc6b1a  localhost/test_export:latest  sh          13 minutes ago  Exited (1) 13 minutes ago              lucid_hamilton
19de69f24391  localhost/test_export:latest  sh          12 minutes ago  Exited (0) 12 minutes ago              tender_morse
[karl@fedora ~]$ podman container rm -f 408e5bbc6b1a 19de69f24391
408e5bbc6b1ab704565c6cfd497c7e46ff2728cffb57113ebdfa796e963f4047
19de69f24391b7d8af9638996437322afd3c82d6ad8707a73ee486baf3339b3a
[karl@fedora ~]$ 
[karl@fedora ~]$ podman image ls -a
REPOSITORY             TAG         IMAGE ID      CREATED            SIZE
localhost/test_export  latest      aec3c4c4804b  About an hour ago  1.06 GB
[karl@fedora ~]$ 
[karl@fedora ~]$ podman image rm -f aec3c4c4804b
Untagged: localhost/test_export:latest
Deleted: aec3c4c4804b2748b7ddd61d7a65926019a30cf2e6d6ef0a1f0aba0310187690
[karl@fedora ~]$ 
[karl@fedora ~]$ podman load < test_export.tar.gz
Getting image source signatures
Copying blob 4c398f2d4043 done  
Copying blob e100e106c3da done  
Copying config aec3c4c480 done  
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/test_export:latest
[karl@fedora ~]$ 
[karl@fedora ~]$ podman image ls -a
REPOSITORY             TAG         IMAGE ID      CREATED            SIZE
localhost/test_export  latest      aec3c4c4804b  About an hour ago  1.06 GB
[karl@fedora ~]$ 
[karl@fedora ~]$ df -hT $HOME
Dateisystem    Typ   Größe Benutzt Verf. Verw% Eingehängt auf
/dev/vda2      btrfs   49G    5,8G   43G   12% /home
[karl@fedora ~]$ 
[karl@fedora ~]$ distrobox-create --image localhost/test_export:latest --name test_export
0b732017a3a9994263ae4136d2f45b0e1bb1ed2e6920e9767bb7a1be3afb3b46
Distrobox 'test_export' successfully created.
To enter, run:
	distrobox-enter --name test_export
[karl@fedora ~]$ 
[karl@fedora ~]$ df -hT $HOME
Dateisystem    Typ   Größe Benutzt Verf. Verw% Eingehängt auf
/dev/vda2      btrfs   49G    6,5G   43G   14% /home
[karl@fedora ~]$ 
[karl@fedora ~]$ distrobox-enter --name test_export
Starting container test_export
run this command to follow along:
	podman logs -f test_export

done!
karl@test_export:~$ gedit
karl@test_export:~$ exit
logout
[karl@fedora ~]$
```

**Comment by 89luca89** [comment] 2022-01-02 12:01
I see you have podman 3.4.4 and btrfs, I had 3.4.2 and XFS
I'll test with a new VM with those specs and see

**Comment by kkarsten62** [comment] 2022-01-02 12:25
And you did a `luca-linux@test:~$ podman stop test` which I did not.
I have uploaded my [export file](https://cloud.karl-karsten.de/index.php/s/SDDGm9fCnZ38Hcw). Maybe you can check with it as well.

**Comment by 89luca89** [comment] 2022-01-02 13:07
I can finally reproduce this on btrfs and podman 3.4.4

[fedora-podman-2.log](https://github.com/89luca89/distrobox/files/7799045/fedora-podman-2.log)

Seems probably something more to do with btrfs because the same installation on XFS does not show this behavior.

As you, I've tested a simple `podman run` and indeed it does NOT increase size.

Testing manually the podman command that creates this problem, it is the ` --userns keep-id`
This does a series of `chmod` on the image inside ~/.local/share/containers in order to keep the IDs mapped between host's and container

Indeed you can reproduce this with a simple:

```shell
[luca-linux@f35 ~]$ podman create --userns keep-id localhost/test_export:latest  sleep infinity
a665c37c356bb9940d092741174f165d0f4998f364cb83eaa4816a0c5bb9c77f
[luca-linux@f35 ~]$ podman images
REPOSITORY             TAG         IMAGE ID      CREATED         SIZE
localhost/test_export  latest      744b80c1805d  55 minutes ago  2.32 GB
```

**Comment by 89luca89** [comment] 2022-01-02 14:31
Seems like I'm able to reproduce this on VMs but not on real hosts
From podman 3.4.0 to 3.4.4

Trying older Fedora VM:
 
- F34 Silverblue, and podman 3.1.0 does NOT do this.
- F34 Workstation, and podman 3.4.2 does do this.
- F34 Workstation, podman downgraded to 3.1.0 does NOT do this.

So here the problem seems to be related to something introduced in podman's `--userns keep-id` between version 3.1.0 and 3.4.2

**Comment by 89luca89** [comment] 2022-01-02 14:56
Reading this issue on podman's repo here: https://github.com/containers/podman/issues/11220

Seems related, the solution they propose is to put

```
[storage]
driver = "overlay"

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
```

in your ~/.config/containers/storage.conf file.

This indeed fixes the issue

**Comment by kkarsten62** [comment] 2022-01-02 16:11
Hi Luca,

yes - I can confirm. A quick check in my VM shows that the size remains on the same size - great, good work!

Karl ..

**Comment by 89luca89** [comment] 2022-01-02 16:48
I'll add this to the readme so that we have this information available and close this

**Closed by 89luca89** 2022-01-02 16:48 UTC
