### ISSUE TITLE
Avoid Appending distroname to exported apps

### ISSUE THREAD

**Issue by rbreaves** [89luca89/distrobox#237] opened 2022-04-16 18:52 UTC
**Is your feature request related to a problem? Please describe.**
I do not want to see the distribution name appended to my exported app desktop shortcuts. Example - "Firefox (on arch)" - I just want to see "Firefox"

**Describe the solution you'd like**
Perhaps an argument added to `distrobox-export --app firefox` to turn off the appending of the distro.

**Describe alternatives you've considered**
Create a script or service that goes and cleans up all (on XXXX) appended names in .desktop files.

**Additional context**
It really looks bad on distros that use Global Menus imo. (If vala-appmenu knew to ignore (on XXXX) then it wouldn't be as big of a deal to me.

**Comment by 89luca89** [comment] 2022-04-16 20:54
Hi @rbreaves 

just use the `--export-label` flag to set a custom one, in this case, you can use an empty space:

`distrobox-export --app gnumeric --export-label " "`

Works as intended

Closing this as this feature would just be a duplicate of an existing one

**Closed by 89luca89** 2022-04-16 20:54 UTC
Labels: enhancement

**Comment by rbreaves** [comment] 2022-04-25 20:06
What about the app title? I am noticing this still appears to be there in the center of the window.

![image](https://user-images.githubusercontent.com/10969616/165165954-420bff42-6f8e-4abb-9aaa-d357a282bb20.png)

**Comment by 89luca89** [comment] 2022-04-25 20:11
> What about the app title? I am noticing this still appears to be there in the center of the window.
> 
> ![image](https://user-images.githubusercontent.com/10969616/165165954-420bff42-6f8e-4abb-9aaa-d357a282bb20.png)

This is because the container hostname is different from the host's one, so it thinks it is a remote application (hence the added title)
You can set the container hostname to the Host's hostname and it should resolve.

Note that this needs a container recreation, as you'll need to specify an init hook for this like explained here:

https://github.com/89luca89/distrobox/blob/main/docs/useful_tips.md#enable-ssh-x-forwarding-when-ssh-ing-in-a-distrobox
