### ISSUE TITLE
[Suggestion] Better organization of desktop files

### ISSUE THREAD

**Issue by RocketRide9** [89luca89/distrobox#865] opened 2023-07-15 18:20 UTC
**Is your feature request related to a problem? Please describe.**
Currently desktop files are stored in `~/.local/share/applications/` by default.

**Describe the solution you'd like**
Create separate folders for each distrobox container. Something like this:

- applications
- - fedora-rawhide
- - - app.desktop
- - - ...
- - archlinux-latest
- - - another-app.desktop
- - - ...

Also since containers are separated it's possible to drop container prefixes.

**Comment by 89luca89** [comment] 2023-08-03 16:33
This is a duplicate of #386

**Closed by 89luca89** 2023-08-03 16:33 UTC
Labels: enhancement
