### ISSUE TITLE
[Discussion] Ubuntu 24.04 container - ALSA lib pcm_dmix.c:1000:(snd_pcm_dmix_open) unable to open slave

### ISSUE THREAD

**Issue by Dunard** [89luca89/distrobox#1374] opened 2024-05-05 09:55 UTC
![Screenshot_20240505_045659](https://github.com/89luca89/distrobox/assets/31096423/08656882-a3c1-4ae4-b40f-9c3e9b2341ad)
How I get this to work? Ubuntu 24.04 container on Fedora 39.

**Comment by Dunard** [comment] 2024-05-06 01:46
distrobox create --name ubuntu2404 --init --image ubuntu:24.04 --additional-packages "systemd libpam-systemd"

distrobox enter ubuntu2404

sudo apt install gweled

gweled

**Comment by shocklateboy92** [comment] 2024-05-16 20:40
Okay, I ran into the same issue on Arch Linux and figured out the solution.

The issue is that I (and presumably Fedora, by default) use pipewire as the audio server, but the default ubuntu image isn't configured to do so. 

If you follow [these 2 steps](https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e?permalink_comment_id=3976215#configure) inside the container to configure alsa to default to using the pipewire alsa module, it'll work.

Does the distrobox team own these images? Can they include this config by default?

**Comment by Dunard** [comment] 2024-05-18 03:53
Thanks. Just need this. sudo apt install pipewire-audio-client-libraries
Switched to Ubuntu 23.10 because of the update will download the beta game version. beta game got a bug that will crash.
The game found it. Audio driver chosen: ALSA
Added this to my notes.

**Comment by 89luca89** [comment] 2024-06-18 15:32
Thanks for investigating @Dunard 
I'll close this, as I've documented your missing package

**Closed** 2024-06-18 15:31 UTC
Labels: bug
