### ISSUE TITLE
[Error] failed to bind mount /run/host/var/log/journal to /var/log/journal

### ISSUE THREAD

**Issue by cristianrz** [89luca89/distrobox#556] opened 2022-12-16 07:42 UTC
**Describe the bug**

Got a distrobox that's been running for weeks, today on restart I got the following error (both on the old container and creating a new one from scratch:

```
$ distrobox-create
(all ok)
$ distrobox-enter my-distrobox
(...)
 Setting up read-only mounts...         	
 Warning: failed to bind mount /run/host/var/log/journal to /var/log/journal Error: An error occurred

An error occurred

An error occurred
```

Restarting didn't help

**To Reproduce**
See above

**Expected behavior**
distrobox goes through the setup process and enters the container

**Logs**
[distrobox-enter.log](https://github.com/89luca89/distrobox/files/10243642/distrobox-enter.log)
[podman-logs-latest.log](https://github.com/89luca89/distrobox/files/10243651/podman-logs-latest.log)

**Desktop (please complete the following information):**

```
$ podman --version
podman version 3.4.4
$ distrobox --version
distrobox: 1.4.1
```

**Comment by 89luca89** [comment] 2022-12-19 13:19
Hi @cristianrz 

this is a duplicate of #545 
Let's discuss there

**Closed by 89luca89** 2022-12-19 13:19 UTC
Labels: bug
