### ISSUE TITLE
[Error] Distrobox-export fails to export app on steam deck

### ISSUE THREAD

**Issue by Doc-4** [89luca89/distrobox#606] opened 2023-02-01 02:36 UTC
Edit: For some reason when I filed this, the template wasn't what was given to me, (mobile problem, maybe?) I've updated the bug report to match the template.
I'm running distrobox with podman on a steam deck with immutable filesystem left enabled. I installed libavcodec58 through apt myself along with pulse audio for audio passthrough as the pre-shipped dependencies weren't able to be loaded (terminal said existing filepaths to them were "not found". So application works fine from terminal at this point, but when I try to export the application from distrobox, the command fails.

I tried this on a separate Ubuntu box by installing the program through apt as a .deb, installing the dependencies, and reproduced the same bug.

I expect export to give me a usable link to the application on the host OS.

If it means anything, the program in question is Jriver Media Center 30, installed with [InstallJRMC](https://git.bryanroessler.com/bryan/installJRMC) which does add it through apt as well.
[DistroboxLog.txt](https://github.com/89luca89/distrobox/files/10823018/DistroboxLog.txt)
[podmanlog.txt](https://github.com/89luca89/distrobox/files/10823019/podmanlog.txt)

**Comment by dtantono** [comment] 2023-02-14 04:13
I second this. I tried gedit and this app does not launch after I tried this command with distrobox-export --app gedit.

**Comment by Doc-4** [comment] 2023-02-24 10:15
I've updated the bug report to be more helpful and provided additional logs, sorry for somehow missing the template first time around.

**Comment by 89luca89** [comment] 2023-02-25 09:27
Hi @Doc-4 
This seems a duplicate of #463 

You should be able to fix it using this fix:

> Add export PATH=$HOME/.local/bin:$HOME/.local/podman/bin:$PATH
> at the end of /etc/profile.

**Closed by 89luca89** 2023-02-25 09:27 UTC

**Comment by Doc-4** [comment] 2023-02-25 18:19
Please reopen, adding this line to etc/profile didn't result in any change. 
![image](https://user-images.githubusercontent.com/60247583/221373103-c02fab07-e6a2-4667-a110-fc35a789e692.png)

I also tried adding it to ~/.bashrc, where the other distrobox run at boot commands live:
![image](https://user-images.githubusercontent.com/60247583/221373255-8fa481a4-f534-4129-b635-3a860ea18327.png)

Still no change.

**Comment by dtantono** [comment] 2023-02-25 23:27
yes same here 
@Doc-4 maybe you can comment in https://github.com/89luca89/distrobox/issues/463 here as well
