### ISSUE TITLE
chdir /run/host//home/<username> no such file or directory on kernel 5.18.4-101.fc35.x86_64

### ISSUE THREAD

**Issue by christofhaerens** [89luca89/distrobox#327] opened 2022-06-17 14:28 UTC
**Describe the bug**
Get a chdir error after last upgrade (which also included a kernel upgrade but not 100% sure if kernel update is to blame)

**To Reproduce**
On fedora 35 with kernel 5.18.4-101.fc35.x86_64
```
[haerench☮bender]-(~) % distrobox enter f36                                                       
Container f36 is not running.
Starting container f36
run this command to follow along:

 podman logs -f f36

 Starting container...                  	 [ OK ]
 Installing basic packages...           	 [ OK ]
 Setting up read-only mounts...         	 [ OK ]
 Setting up read-write mounts...        	 [ OK ]
 Setting up host's sockets integration...	 [ OK ]
 Integrating host's themes, icons, fonts...	 [ OK ]
 Setting up package manager exceptions...	 [ OK ]
 Setting up sudo...                     	 [ OK ]
 Setting up groups...                   	 [ OK ]
 Setting up users...                    	 [ OK ]
 Executing init hooks...                	 [ OK ]

Container Setup Complete!
Error: chdir `/run/host//home/haerench`: No such file or directory: OCI runtime attempted to invoke a command that was not found

An error occurred

An error occurred

```

**Additional context**
```
[haerench☮bender]-(~) % distrobox --version
distrobox: 1.3.1
[haerench☮bender]-(~) % cat /etc/fedora-release 
Fedora release 35 (Thirty Five)
[haerench☮bender]-(~) % uname -a
Linux bender 5.18.4-101.fc35.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 15 13:45:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Logs**
see attached files verbose.log and podman.log

**Desktop (please complete the following information):**
 - Are you using podman or docker? podman
 - Which version or podman or docker? 3.4.7
 - Which version of distrobox? 1.3.1

**Comment by christofhaerens** [comment] 2022-06-17 14:30
[verbose.log](https://github.com/89luca89/distrobox/files/8928444/verbose.log)
[podman.log](https://github.com/89luca89/distrobox/files/8928453/podman.log)

**Comment by 89luca89** [comment] 2022-06-17 16:26
Hi @christofhaerens 

this seems strange, like you don't have `/run/host` mounted inside the container
sadly I cannot reproduce this

Can you try with a newly created container?

**Comment by christofhaerens** [comment] 2022-06-20 06:42
The logs I provided where from a newly distrobox-create container. A new kernel update was available this morning, installed it and tried both a new and old distrobox, but same issue.
If I run with `--no-workdir` it works. For me distrobox is handy to run different firefox browsers next to each other and with different settings / plugins / versions.  So I mainly use the `--no-tty -e firefox` to my containers option and this seems still to work together with the `--no-workdir` option

**Comment by 89luca89** [comment] 2022-06-20 08:56
Ah ok this seems to be it, let me know if you resolve by using bind mount on the host
or you could set HOME to `/data/home` and should also work (need recreating the container)

**Comment by 89luca89** [comment] 2022-06-22 07:03
@christofhaerens I'm closing this as it's not a distrobox bug

**Closed by 89luca89** 2022-06-22 07:03 UTC
Labels: bug

**Comment by christofhaerens** [comment] 2022-06-23 09:03
Finally had a restart window for the system this morning and replacde the link with a bind mount. All is working ok now. Thxs for the help,
