### ISSUE TITLE
[Error] Getting "Transaction Failed" when trying to install distrobox inside the container

### ISSUE THREAD

**Issue by tunix** [89luca89/distrobox#339] opened 2022-06-26 20:45 UTC
**Describe the bug**

I'm trying to install distrobox inside the container and getting "Transaction failed" error. Please see the output below:

```
sudo dnf install distrobox

Last metadata expiration check: 0:32:22 ago on Paz 26 Haz 2022 23:05:10.
Dependencies resolved.
========================================================================================================================================================================================================
 Package                                         Architecture                                 Version                                               Repository                                     Size
========================================================================================================================================================================================================
Installing:
 distrobox                                       noarch                                       1.3.1-1.fc36                                          updates                                        72 k

Transaction Summary
========================================================================================================================================================================================================
Install  1 Package

Total download size: 72 k
Installed size: 199 k
Is this ok [y/N]: y
Downloading Packages:
distrobox-1.3.1-1.fc36.noarch.rpm                                                                                                                                       203 kB/s |  72 kB     00:00
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                    40 kB/s |  72 kB     00:01
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                1/1
  Installing       : distrobox-1.3.1-1.fc36.noarch                                                                                                                                                  1/1
Error unpacking rpm package distrobox-1.3.1-1.fc36.noarch
  Verifying        : distrobox-1.3.1-1.fc36.noarch                                                                                                                                                  1/1

Failed:
  distrobox-1.3.1-1.fc36.noarch

Error: Transaction failed
```

**To Reproduce**

Trying to install distrobox package produces the error:

`sudo dnf install distrobox`

**Expected behavior**

The package should be installed without any errors.

**Desktop**

 - Are you using podman or docker? podman
 - Which version or podman or docker? 4.1.0
 - Which version of distrobox? 1.2.15

**Comment by 89luca89** [comment] 2022-06-27 07:59
Hey @tunix 

to be clear, you're installing `distrobox` inside a distrobox container?

If yes, then I think the problem is `/usr/bin/distrobox-export` that is a mount read-only from the host, and the rpm tries to overwrite it
That file must be in sync with the version of distrobox you have on the host

If you want distrobox inside the container, please use the official `install` script, and put it in a different path (`/usr/local/`  for example)

Be aware that when you will use `distrobox-export` from a newer version it is possible to have compatibility problems when you'll launch exported stuff from the host.

Nested distrobox should be ok, but mixing versions should not.

Closing this as it's not a bug

**Closed by 89luca89** 2022-06-27 07:59 UTC
Labels: bug

**Comment by tunix** [comment] 2022-06-27 08:09
The reason I'm trying to install distrobox inside a distrobox container is to have access to `distrobox-host-exec` command. I'm trying to use `distrobox` command inside the distrobox container (I was planning to alias it to `distrobox-host-exec`) as the container is my main shell. (I was looking for ways to manage distrobox containers from one particular container that I have)

**Comment by 89luca89** [comment] 2022-06-27 08:12
Well you can install using the `install` command in the main page, just use `-p /usr/local` and you should be ok
